### ISSUE TITLE
Synchronizing issue

### ISSUE THREAD

**Issue by butthead007** [loki-project/loki#107]
Hi, 
The synchronization started but I get the following error in the attachment). I bought tokens but don't see any in my wallet because the synch process isn't working properly.  What seems to be the problem?

![loki error](https://user-images.githubusercontent.com/41707264/43229731-1b08b7f8-9066-11e8-8b80-79a4a824bcd9.jpg)

**Comment by Doy-lee** [comment]
I recommend making a backup of what you currently synced and trying to sync against from scratch past that point. Alternatively you bootstrap a remote node whilst syncing so you can see your funds using 
--bootstrap-daemon-address <arg>, an example remote nodes is doopool.xyz:22020, more remote nodes available through our communication channels (discord, telegram).

The nature of blockchain is that you won't see your funds until you receive the block in the chain that has your transaction which is always going to be near the tail end, i.e. at this point the 60,000th block.
