### ISSUE TITLE
Suggestion: Hard code service node port usage.

### ISSUE THREAD

**Issue by kingsley22** [loki-project/loki#142]
Hard code the/any SN port usage, so it cannot be altered without re-compiling, to make it more difficult (obviously not impossible) to run 2 SN's on the single machine.

**Comment by Haafingar** [comment]
Not a terrible idea. Could make the default for SNs to block any traffic from non-defualt port numbers. Would be enforcable by consensus by the majority of nodes voting off non-defualt ported nodes. Then again, I'm not currently sure of the the way that SN registrations do this. Is a service node bound to the whole IP @jcktm ?

Would this also make it more difficult for someone to add another IP to their machine to avoid having to run multiple servers? They couldnt run the daemon from the same port, but then they might just be able to run one daemon which is referred to twice in the SN list?

Of course, most of these problems go away when bandwidth voting comes in. In this case, what is being enforced the question: "is each registered node able to account for a minimum bandwidth standard?"

If I have a massive connection able to support 50MB/s, and the standard is only 5MB/s, should I really be stopped from running 10 SNs on the one connection if I can support that bandwidth? @KeeJef

**Comment by jcktm** [comment]
> Is a service node bound to the whole IP @jcktm ?

No, currently it is possible to run service nodes on the same machine. In fact we do this for testing.

My feeling is they wont be able to meet the bandwidth requirements on the same machine, or at least it will be more economical to use multiple machines.

**Comment by KeeJef** [comment]
Running multiple service nodes on the same machine brings up location diversity concerns. Even if servers are rented in the same data center i would rather that than easily run on the same machine. The more centralized service node operation the easier passive surveillance becomes.  

Putting sensible barriers to this type of operation seems valuable, although i don't think this should be enforced at a consensus level, any truly motivated person who wishes to centralized can remove software prevention, and unless you limit by IP address there is nothing stopping someone running multiple Service Nodes on the same machine (assuming single NICs per machine). However it will encourage most users to separate operation to one Service node per IP address, likely leading to a more diverse network.

As far a the possibility of doing this and still passing Bandwidth tests, i think its very probable, 
(of course this depends on how we set bandwidth requirements) but even a higher estimate of 10 - 15 MiB's a server can easily do 30 - 40 MiB's allowing them to pass the Bwith tests for 2 Service Nodes.

**Comment by richardbeee** [comment]
I would suggest rethinking why running multiple SN's from the same machine is considered an issue in the first place.

If multiple SN's running from the same machine is able to keep up with the demands from the network - why is it an issue? Is it the risk that if you compromise a SN that you potentially compromise 2? Why?


Cheers, joobie

**Comment by jcktm** [comment]
> Running multiple service nodes on the same machine brings up location diversity concerns. Even if servers are rented in the same data center i would rather that than easily run on the same machine. The more centralized service node operation the easier passive surveillance becomes.

**Comment by richardbeee** [comment]
If you are concerned about passive surveillance - would it not be more concerning for multiple nodes existing in the same data center?

In the case of an individual - one could spawn multiple nodes across multiple data centers and have passive surveillance across all dispersed nodes.

In the case of a data center housing multiple nodes from multiple individuals - this would enable the datacenter to passively survey multiple individuals.

Cheers, joobie

**Comment by majestrate** [comment]
using a fixed port makes blocking the entire network super trivial.

**Comment by kimnnmadsen** [comment]
> > Running multiple service nodes on the same machine brings up location diversity concerns. Even if servers are rented in the same data center i would rather that than easily run on the same machine. The more centralized service node operation the easier passive surveillance becomes.

I would say this is a weak argument. You are only increasing cost for running multiple service nodes. And it is trivial to counter with contianers or virtual machines.
Should the limiting factor not be your stake? Instead of some arbitrary hardcoded limitations?

**Comment by KeeJef** [comment]
I think the most sound argument against this is the one Jeff has given which is the banning of specific ports if we hard coded port numbers would necessitate a new release for the general public, which is not great. 

with that i'm going to close this issue
