### ISSUE TITLE
`make release-static` and boost: No suitable build variant has been found

### ISSUE THREAD

**Issue by martin-braun** [loki-project/loki#1652]
**Describe the bug**
Static build cannot resolve boosts, claiming "No suitable build variant has been found".

**To Reproduce**

```
sudo apt update && sudo apt install build-essential cmake pkg-config libboost-all-dev libzmq3-dev libsodium-dev libunwind8-dev liblzma-dev libreadline6-dev doxygen graphviz libpgm-dev libsqlite3-dev libcurl4-openssl-dev
cmake --version # 3.18.4
apt-cache policy libboost-dev # installed and candidate: 1.74.0.3 (only available one)
make release-static
```

**Expected behaviour**
It should build.

**Current Behaviour**
```
-- Using C security hardening flags:  -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -Wformat -Wformat-security -fstack-protector -fstack-protector-strong -fcf-protection=full -fstack-clash-protection
-- Using C++ security hardening flags:  -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -Wformat -Wformat-security -fstack-protector -fstack-protector-strong -fcf-protection=full -fstack-clash-protection
-- Using linker security hardening flags:  -Wl,-z,relro -Wl,-z,now -Wl,-z,noexecstack
CMake Error at /usr/lib/x86_64-linux-gnu/cmake/Boost-1.74.0/BoostConfig.cmake:141 (find_package):
  Found package configuration file:

    /usr/lib/x86_64-linux-gnu/cmake/boost_system-1.74.0/boost_system-config.cmake

  but it set boost_system_FOUND to FALSE so package "boost_system" is
  considered to be NOT FOUND.  Reason given by package:

  No suitable build variant has been found.

  The following variants have been tried and rejected:

  * libboost_system.so.1.74.0 (shared, Boost_USE_STATIC_LIBS=ON)

  * libboost_system.a (shared runtime, Boost_USE_STATIC_RUNTIME=ON)

Call Stack (most recent call first):
  /usr/lib/x86_64-linux-gnu/cmake/Boost-1.74.0/BoostConfig.cmake:258 (boost_find_component)
  /usr/share/cmake-3.18/Modules/FindBoost.cmake:448 (find_package)
  CMakeLists.txt:791 (find_package)


-- Configuring incomplete, errors occurred!
See also "release/CMakeFiles/CMakeOutput.log".
See also "release/CMakeFiles/CMakeError.log".
make: *** [Makefile:104: release-static] Error 1
```

**Additional Information (please complete the following information):**
 - Operating System: Debian Bullseye
 - Local node (Parallels VM on MacOS)
 - [7bda65c5d2f615c317682ee82cd8251d35a60b69](https://github.com/oxen-io/oxen-core/commit/7bda65c5d2f615c317682ee82cd8251d35a60b69) (latest)

I've read about a possible version mismatch between CMake and Boost, but downgrading Boost is not possible with `apt`. I also read that `find_package(Boost ..)` should solve this issue and I can see `FindBoost` is not used anymore, so what is going on? I'd like to get a portable `oxend`.

Could anybody give guidance on how to compile a static build of the daemon?

**Links**

- https://stackoverflow.com/a/55374913/1540350
- https://stackoverflow.com/a/42124857/1540350

**Comment by jagerman** [comment]
For make a fully static oxend (and other binaries) I suggest using:

```
mkdir build-static
cd build-static
cmake .. -DBUILD_STATIC_DEPS=ON -DCMAKE_BUILD_TYPE=Release
```
which will download and build static versions of the various dependencies.  (This is essentially [how we build](https://github.com/oxen-io/oxen-core/blob/7bda65c5d2f615c317682ee82cd8251d35a60b69/.drone.jsonnet#L317) the static releases that we use in the wallet and on the download page).

**Comment by martin-braun** [comment]
@jagerman Thanks a lot for that, the build successfully started to compile using your command. I can see this is the documented way to compile the storage server as well. It seems the `Makefile` of oxen-core is quite outdated in that regard, because it contains:

```Makefile
cmake-release:
	mkdir -p $(builddir)/release
	cd $(builddir)/release && cmake -D CMAKE_BUILD_TYPE=Release $(topdir)

release: cmake-release
	cd $(builddir)/release && $(MAKE)

release-test:
	mkdir -p $(builddir)/release
	cd $(builddir)/release && cmake -D BUILD_TESTS=ON -D CMAKE_BUILD_TYPE=Release $(topdir) && $(MAKE) && $(MAKE) test

release-all:
	mkdir -p $(builddir)/release
	cd $(builddir)/release && cmake -D BUILD_TESTS=ON -D CMAKE_BUILD_TYPE=Release $(topdir) && $(MAKE)

release-static:
	mkdir -p $(builddir)/release
	cd $(builddir)/release && cmake -D STATIC=ON -D ARCH="x86-64" -D BUILD_64=ON -D CMAKE_BUILD_TYPE=Release $(topdir) && $(MAKE)

release-full-static:
	mkdir -p $(builddir)/release-static
	cd $(builddir)/release-static && cmake -DBUILD_STATIC_DEPS=ON -DCMAKE_BUILD_TYPE=Release $(topdir) && $(MAKE)

release-full-static-archive: release-full-static
	cd $(builddir)/release-static && $(MAKE) strip_binaries && $(MAKE) create_archive
```

The documentation still recommends to run `make release-static` for a static build. While I don't feel confident enough to hack within the `Makefile` extensively, but if you wish, I can make a PR to update the `README.md` properly.

## It's still not quite there

There seem to be more problems down the line though: 

```
[ 20%] Built target randomx
-- Using src='https://zlib.net/zlib-1.2.13.tar.xz'
-- Retry after 60 seconds (attempt #5) ...
-- Using src='https://zlib.net/zlib-1.2.13.tar.xz'
CMake Error at zlib_external-stamp/download-zlib_external.cmake:159 (message):
  Each download failed!

    error: downloading 'https://zlib.net/zlib-1.2.13.tar.xz' failed
```

Yes, the link is dead, but the host itself is reachable. This is a different problem ...

## EDIT: I found it

Now it's located at https://zlib.net/fossils/zlib-1.2.13.tar.gz, so the StaticBuild.cmake needs to be updated as well.

**Comment by martin-braun** [comment]
@jagerman Thank you for everything so far and I hope you had a great weekend so far. ~~I'm still facing issues with the static build on Debian Bullseye though #1654~~

I will try to solve this by my own, but as always, I appreciate your input and shared knowledge. It would be very helpful to get some assistance on that, if possible. (EDIT: I found a solution to the problem! Thanks anyways!)

Off topic: I realize that all my PRs fail because the drone CI fails, but it fails for unrelated reasons. It's unfortunate, because it blocks PRs. Is there any issue to track those issues as of now?

Looking forward to contribute. :)
