### ISSUE TITLE
Add Configurable URL Option for Staking Submission API

### ISSUE THREAD

**Issue by javabudd** [loki-project/loki#1741]
**Add Configurable URL Option for Staking Submission API**

---

**Description:**

Currently, the URL for submitting staking information to the staking API (`ssb.oxen.observer`) is hardcoded. To improve flexibility and adaptability in various environments, we should  make this URL configurable through a CLI option. This is marked as a TODO in the application.

---

**Task Breakdown:**

- **Refactor the submission URL:**  
  Replace the hardcoded `https://ssb.oxen.observer/api/store/{}` URL (`src/daemon/rpc_command_executor.cpp:2785`) with a configurable option from the application's configuration.
  
- **Add new config option:**  
  Introduce a new configuration entry (e.g., `staking_api_url`) that will allow the user to specify the base URL for the staking submission API.

- **Fallback mechanism:**  
  Ensure that the code falls back to the current hardcoded URL if the new config option is not set, maintaining backward compatibility.

- **Update the code:**  
  Modify the logic within the submission process to use the URL from the configuration, replacing:
  ```cpp
  auto url = cpr::Url{"https://ssb.oxen.observer/api/store/{}"_format(snode_pubkey)};
  ```
  with the configurable URL.

- **Testing:**
  - Ensure that the submission works correctly using both the default hardcoded URL and a user-specified URL.
  - Test various edge cases like invalid URLs or missing configuration.

---

**Acceptance Criteria:**

1. The API URL for staking submission is configurable via a config option.
2. The application falls back to the current hardcoded URL if the config option is not set.
3. The submission process behaves the same with both the default and custom URLs.
4. Error handling for incorrect or missing URLs is implemented.

**Comment by jagerman** [comment]
#1759 more or less addresses this.

**Comment by javabudd** [comment]
https://github.com/oxen-io/oxen-core/pull/1759
