### ISSUE TITLE
Fix block-height estimation code for test/stagenet

### ISSUE THREAD

**Issue by jcktm** [loki-project/loki#222]
> See: https://github.com/loki-project/loki/commit/e88b5661e27fa9aefc91468776be44e6955346f2
> 
> Since testnet/stagenet has been frozen/being unused for some time, the block height estimation code is overestimating what height wallets should restore from causing 0 balances to show.

**Comment by jcktm** [comment]
@Doy-lee said:
> Afaik Sacha had a look and said the estimation code was ok. There's two places where this estimation code happens if I remember correct. There's one in the simplewallet and another internally somewhere because I think the GUI and CLI estimate differently

**Comment by Doy-lee** [comment]
Duplicate: https://github.com/loki-project/loki/issues/131
