### ISSUE TITLE
Investigate by lokiblocks shows 0% portions for registration TX's when it shouldn't 

### ISSUE THREAD

**Issue by jcktm** [loki-project/loki#229]
@Doy-lee Is this still a problem?

**Comment by Doy-lee** [comment]
Example:
https://lokitestnet.com/tx/618907c06c36fc18a0a0101fba7891482e53bc004896c35a3a40b7ae1d344ff5

Yes. Though this I have reasonable suspicion it's a loki onion explorer problem and not a daemon problem. So I'd start investigating the contents the explorer receives before going to the daemon.

**Comment by Doy-lee** [comment]
https://github.com/loki-project/loki/pull/310
