### ISSUE TITLE
Improve the pop_blocks command

### ISSUE THREAD

**Issue by jcktm** [loki-project/loki#232]
See the todos in code

**Comment by Doy-lee** [comment]
See: https://github.com/loki-project/loki/issues/227

We could improve the blockchain_utilities version by making it rollback service node list state and remove the RPC version I added.

**Comment by Doy-lee** [comment]
Fixed in: https://github.com/loki-project/loki/pull/188

**Comment by jcktm** [comment]
Doyle what's your personal email? I want to send you an email

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
