### ISSUE TITLE
Mitigate autostakes ability to double-stake if block times are abnormal

### ISSUE THREAD

**Issue by jcktm** [loki-project/loki#236]
@Doy-lee wrote:
> Current solution: https://github.com/loki-project/loki/pull/203 increases the time between autostakes.
> 
> For future reference. the robust solution is to save the last block you tried autostaking with and from there, check the block backlog and wait until that many blocks has transpired before trying to restake.

I'd implement this by checking if there is a registration tx for your pubkey in the tx pool already. If it's not in the snode list and not in the pool, then stake, otherwise don't.

**Comment by Doy-lee** [comment]
I wasn't sure if the wallet has an easy way to inspect the TX pool. It looks like getting the contents be done using this https://getmonero.org/resources/developer-guides/daemon-rpc.html#get_transaction_pool, parse the binary blobs it gives you, extract the registration tx and then do the check.

**Comment by Doy-lee** [comment]
Non issue with https://github.com/loki-project/loki/pull/406 which removes auto-staking functionality.
