### ISSUE TITLE
register_service_node command accepted by wallet without sufficient balance unlocked

### ISSUE THREAD

**Issue by hoidsflute** [loki-project/loki#243]
On testnet:

I was able to `register_service_node` without sufficient balance unlocked.  I received the `transaction successfully submitted` notice, but the service node was not registered.  I should received an error that I could not `register_service_node` until I had 100 TLOKI balance unlocked.

**Comment by Doy-lee** [comment]
This is in place to facilitate the ability to split the cost of getting a service node onto the network. The minimum contribution to setting up a service node for operators is 25%, other people can then identify your node, say on lokitestnet.com and see your service node is partially registered and has 75% left of Loki required to become a fully registered service node.

They may then stake in the wallet-cli towards your node and receive a service node reward proportional to the amount they stake.

On version Loki 'Magic Mani' (v1.0.0-rc-b73aa8e) (i.e. release candidate 3, rc3), 

1. I'm unable to register_service_node with my insufficient balance if I reserve more than I have in prepare_registration.
2. If I however prepare_registration and reserve as much balance as I have, I'm able to partially register my service node and open it up for pooling.

It sounds like you fall under the second case here.

**Comment by hoidsflute** [comment]
I could understand this in a case that I had a sufficient balance unlocked.  I'm not referring to whether I had a _sufficient_ balance, but if it was _unlocked_. 

In other words, I can't spend 100 LOKI in a typical transaction until at least 100 LOKI are unlocked (required # confirmations reached) in my wallet.  Why should I be able to submit a timelock transaction without the required # of confirms, even if it doesn't register?  It should read an error if that is attempted.

**Comment by Doy-lee** [comment]
On version Loki 'Magic Mani' (v1.0.1-ffdf682), I'm unable to reproduce this. My steps to reproduce,

- Launch lokid on its own private blockchain like, `lokid --testnet --offline --data-dir . --service-node`
- Create wallet 1 with wallet-cli in testnet mode `loki-wallet-cli --testnet`
- Mine 50+ blocks into wallet 1
- Stop mining into wallet 1
- Create wallet 2 with wallet-cli in testnet mode `loki-wallet-cli --testnet`
- Transfer from wallet 1 to wallet 2, 125 Loki.
- Mine 1 block in the daemon to wallet 1
- Wallet 2 now has, `Balance: 125.000000000, unlocked balance: 0.000000000`
- Prepare registration in the daemon for wallet 2, auto staking turned off, entire stake to be contributed by Wallet 2.
- Enter the registration command into Wallet 2, which returns

> [wallet T6TG2V]: register_service_node [...]
Wallet password: 
Error: Not enough money in unlocked balance
Wait for transaction to be included in a block before registration is complete.
Use the print_sn command in the daemon to check the status.

I get an error and the funds are still in my wallet. Granted, if these lines

> Wait for transaction to be included in a block before registration is complete.
Use the print_sn command in the daemon to check the status.

Is what you're concerned about, I've raised an issue that we should not be displaying those messages if it fails https://github.com/loki-project/loki/issues/258
