### ISSUE TITLE
Error: Failed to initialize ring database: privacy enhancing features will be inactive

### ISSUE THREAD

**Issue by pnahapkap** [loki-project/loki#245]
![new-loki-cli-wallet-error](https://user-images.githubusercontent.com/26846787/45602507-c8db6300-ba49-11e8-80ae-d96b87096629.png)

I've just created cli wallet using loki-windows-x64-1.0.0-rc.3 and found 
Error: Failed to initialize ring database: privacy enhancing features will be inactive

never found issue like this before, using local daemon and remote node to sync is still the same

need help
thanks

**Comment by Doy-lee** [comment]
This means the daemon is looking for the folder ~/.shared-ringdb, if you have that folder try renaming it and relaunching the wallet cli and letting it regenerate it, then you may copy back the data in and seeing if there was some unusual permissions issues or not stopping it from reading the files.
