### ISSUE TITLE
Lokid went into berserker mode

### ISSUE THREAD

**Issue by Lyndros** [loki-project/loki#247]
Hi guys, 

After running several days the RC3 synched to the mainnet, there waas a point where loki daemon started to do strange things and dumped huge amount of stack traces to my log file. Filling out my HD within some hours....

-rw-r--r-- 1 snode snode 100M Sep 17 13:33 loki.log-2018-09-17-11-33-59
-rw-r--r-- 1 snode snode 100M Sep 17 13:34 loki.log-2018-09-17-11-34-57
-rw-r--r-- 1 snode snode 100M Sep 17 13:35 loki.log-2018-09-17-11-35-57
-rw-r--r-- 1 snode snode 100M Sep 17 13:36 loki.log-2018-09-17-11-36-56
-rw-r--r-- 1 snode snode 100M Sep 17 13:38 loki.log-2018-09-17-11-38-52
-rw-r--r-- 1 snode snode 100M Sep 17 13:39 loki.log-2018-09-17-11-39-52
-rw-r--r-- 1 snode snode 100M Sep 17 13:40 loki.log-2018-09-17-11-40-53
-rw-r--r-- 1 snode snode 100M Sep 17 13:43 loki.log-2018-09-17-11-43-05
-rw-r--r-- 1 snode snode 100M Sep 17 13:44 loki.log-2018-09-17-11-44-05
018-09-17 12:00:19.022 [P2P9]  INFO    stacktrace      src/common/stack_trace.cpp:164      [15] /home/snode/loki-linux-x64-1.0.0-rc.3/lokid:boost::asio::detail::completion_handler<boost::asio::detail::rewrapped_handler<boost::asio::detail::binder2<boost::asio::detail::wrapped_handler<boost::asio::io_context::strand, boost::_bi::bind_t<void, boost::_mfi::mf2<void, epee::net_utils::connection<epee::levin::async_protocol_handler<nodetool::p2p_connection_context_t<cryptonote::cryptonote_connection_context> > >, boost::system::error_code const&, unsigned long>, boost::_bi::list3<boost::_bi::value<boost::shared_ptr<epee::net_utils::connection<epee::levin::async_protocol_handler<nodetool::p2p_connection_context_t<cryptonote::cryptonote_connection_context> > > > >, boost::arg<1> ()(), boost::arg<2> ()()> >, boost::asio::detail::is_continuation_if_running>, boost::system::error_code, unsigned long>, boost::_bi::bind_t<void, boost::_mfi::mf2<void, epee::net_utils::connection<epee::levin::async_protocol_handler<nodetool::p2p_connection_context_t<cryptonote::cryptonote_connection_context> > >, boost::system::error_code const&, unsigned long>, boost::_bi::list3<boost::_bi::value<boost::shared_ptr<epee::net_utils::connection<epee::levin::async_protocol_handler<nodetool::p2p_connection_context_t<cryptonote::cryptonote_connection_context> > > > >, boost::arg<1> ()(), boost::arg<2> ()()> > > >::do_complete(void, boost::asio::detail::scheduler_operation, boost::system::error_code const&, unsigned long)+0x18b [0x55d1df03a76b]

**Comment by Lyndros** [comment]
tried again and still same issue, resynch from scratch same results:

2018-09-18 13:26:46.896 [P2P4]  INFO    stacktrace      src/common/stack_trace.cpp:125  Exception: cryptonote::BLOCK_DNE
2018-09-18 13:26:46.903 [P2P4]  INFO    stacktrace      src/common/stack_trace.cpp:125  Exception: cryptonote::BLOCK_DNE
2018-09-18 13:26:46.911 [P2P4]  INFO    stacktrace      src/common/stack_trace.cpp:125  Exception: cryptonote::BLOCK_DNE

**Comment by Doy-lee** [comment]
This appears to be addressed here.
https://github.com/monero-project/monero/pull/3726

I'll pull in the fix sometime in the next 24hours and get it sorted.

**Comment by Doy-lee** [comment]
This issue seems to be more prevalent than we expected with more people being affected than it initially seemed. A patch has been released as Loki v1.0.1 and addressed here (https://github.com/loki-project/loki/releases/tag/v1.0.1) which fixes this.

**Comment by Lyndros** [comment]
Thank you man! great job!
