### ISSUE TITLE
Problem with sharing the LMDB database

### ISSUE THREAD

**Issue by 0x00031337** [loki-project/loki#261]
We can not really use the facilities introduced some time ago by the Monero team. It's about using one LMDB database for several Loki daemons. Limiting the concurrency of threads causes that the synchronization of the database is reported in the log, but the blochchain in the database is not changed. Not limiting, in turn, means that the log shows that the maximum number of threads has been exceeded and the daemon dies.

3 daemons runing:
```
@400000005ba75a800820d174 2018-09-23 09:18:46.136       [P2P7]  INFO    global  src/cryptonote_protocol/cryptonote_protocol_handler.inl:309     [116.50.169.42:22022 OUT] Sync data returned a new top block candidate: 103208 -> 103224 [Your node is 16 blocks (0 days) behind]
@400000005ba75a800820e8e4 SYNCHRONIZATION started
@400000005ba75b1934788c6c 2018-09-23 09:21:19.880       [P2P3]  INFO    global  src/p2p/net_node.inl:216        Host 199.195.250.169 blocked.
@400000005ba75b791eee7ec4 2018-09-23 09:22:55.518       [P2P9]  INFO    global  src/p2p/net_node.inl:216        Host 144.217.13.61 blocked.
@400000005ba75bd915a6afbc 2018-09-23 09:24:31.363       [P2P5]  INFO    global  src/p2p/net_node.inl:216        Host 51.15.59.137 blocked.
@400000005ba75c0118cd9a0c 2018-09-23 09:25:11.416       [P2P2]  INFO    global  src/cryptonote_protocol/cryptonote_protocol_handler.inl:309     [144.217.243.15:22022 OUT] Sync data returned a new top block candidate: 103208 -> 103229 [Your node is 21 blocks (0 days) behind]
@400000005ba75c0118cdad94 SYNCHRONIZATION started
```
after stopping two processes:
```
@400000005ba75da73813eb3c 2018-09-23 09:32:13.939       [P2P9]  INFO    global  src/cryptonote_protocol/cryptonote_protocol_handler.inl:1615    SYNCHRONIZED OK
@400000005ba75da7389ca33c 2018-09-23 09:32:13.949       [P2P8]  INFO    global  src/cryptonote_protocol/cryptonote_protocol_handler.inl:1225    [137.74.148.229:56014 INC]  Synced 103231/103231
@400000005ba75da739bbfdbc 2018-09-23 09:32:13.968       [P2P8]  INFO    global  src/cryptonote_protocol/cryptonote_protocol_handler.inl:1615    SYNCHRONIZED OK
```
and without limiting:
```
@400000005ba66bb2309a2574 2018-09-22 16:19:52.815<----->    7f7e4b96d700<------>WARN <->blockchain.db.lmdb<---->src/blockchain_db/lmdb/db_lmdb.cpp:75<->Failed to create a read transaction for the db: MDB_READERS_FULL: Environment maxreaders limit reached
```
Concurrency limited to: 60, 40, 32, 20, 10 - same results.

**Comment by msgmaxim** [comment]
As far as I can tell the problem can be reduced to the following scenario:

1. Daemon A receives tx A, saves it to DB and updates its state (namely `m_txs_by_fee_and_receive_time`).
2. Daemon B receives tx B, saves it to DB and updates its state.
3. When, say, daemon A receives a block with transactions A and B, it cannot find tx B in its `m_txs_by_fee_and_receive_time` and thus fails to add the block. Likewise, daemon B would not able to find tx A, even though both transactions are recorded in the DB.

Monero has the same problem: two daemons stop accepting blocks if they use the same DB. There is nothing in the codebase that keeps `m_txs_by_fee_and_receive_time` and the database in sync.

**Comment by msgmaxim** [comment]
I [re-posted](https://github.com/monero-project/monero/issues/4486) this issue on Monero's repository. For now, this will probably be a low priority issue for Loki.

**Comment by jagerman** [comment]
Worth noting that this is apparently fixed upstream now (and is included in the 3.0.0 beta).  I have yet to test it, though.

**Comment by Doy-lee** [comment]
Fixed in: https://github.com/monero-project/monero/pull/4768

**Comment by qm3ster** [comment]
Certified
> Miner tx failed validation: Service node reward winner is incorrect! Expected true, block has true

moment, if you know what I'm saying ;)
