### ISSUE TITLE
Known ring does not include the spent output

### ISSUE THREAD

**Issue by podvodnik** [loki-project/loki#263]
After the update to the last version and after the fork I noticed the following error:

2018-09-23 20:21:37.125 [RPC0]  WARN    net.http        src/wallet/wallet_errors.h:827  /home/test/loki-101/src/wallet/wallet2.cpp:6089:N5tools5error21wallet_internal_errorE: Known ring does not include the spent output: 1299652

And now this coins are stuck in the wallet and I cannot send them anywhere.
Rescanning the blockchain did not help, rescanning spent outputs too.
restoring wallet from the seed also.

**Comment by podvodnik** [comment]
I was able to send the money by using different daemon on other server.
Seems there is something wrong in the local blockchain of the local daemon. I also tried to cut ~20000 blocks so ending ~ 85000 and downloading blockchain from there, did not help.

**Comment by Doy-lee** [comment]
This looks possibly related to https://github.com/monero-project/monero/issues/3539

In which case we need to pull in the fix.
