### ISSUE TITLE
Proposed relaxation of contributor rules

### ISSUE THREAD

**Issue by jagerman** [loki-project/loki#294]
Currently a shared service node requires 25% contribution from all but the final contributor.  This rule makes sense in that you don't want a small contributor to be able to jump in and thus require someone else to finish off with a larger stake.

It should be possible, however, to still prevent this behaviour with a slight relaxation of the rules to base the requirement on the outstanding amount rather than the total stake.

I'd like to suggest a rule where each contributor to a pool with N contribution spots remaining must contribute at least 1/N of the remaining stake (rather than 1/4 of the total stake).  So, for example, if an operator sets up a SN with an operator stake of 40%, this would mean the next contributor would only need to contribute 20% (i.e. 1/3 of the outstanding amount).  If the second contributor instead contributed 30%, then the third contributor would require a minimum 15% stake.  The fourth contributor would, of course, have to finish off the pool.

This would, I believe, make it a little bit easier for contributors with somewhat less than 25% to still find service nodes for their stakes by allowing a somewhat reduced requirement on "overfilled" SNs awaiting stakes.  It would help out shared stake SN operators by making it somewhat easier to find stakes, particularly if they (or a second contribute) contribute more.  It would also allow operators who contribute substantially more than 25% to justify charging higher fees (imagine an operator who contributes 70% himself then sets a higher fee for allowing three small 10% contributors).  And lastly, it would preserve the important property that no one can ever make a contribution that requires a *larger* contribution from later participants to complete a stake.

**Comment by KeeJef** [comment]
Sounds like a good idea, i don't have any issues with this. 25% for each contributor except the last was only really chosen for the sake of simplicity.

**Comment by Doy-lee** [comment]
Obsolete with Infinite Staking https://github.com/loki-project/loki/pull/406 The new rules are as follows, there's a maximum of 4 contributions per node. You must contribute the max(your reserved amount, 1/remaining contributions to node * staking requirement)
