### ISSUE TITLE
Synchronization "killed" 

### ISSUE THREAD

**Issue by Kiefler** [loki-project/loki#295]
When starting to synchronize my server it stops after a few blocks and shows the message "killed".

What am I doing wrong here?
<img width="1124" alt="schermafbeelding 2018-10-22 om 17 12 59" src="https://user-images.githubusercontent.com/7976852/47301192-a62b0400-d61e-11e8-84b0-cea88747e8e8.png">

**Comment by Doy-lee** [comment]
This is a generic Linux error, https://stackoverflow.com/questions/726690/what-killed-my-process-and-why

i.e. The OS terminated the process. My guess is you don't have a swap file or are just using a server with insufficient memory. Swap file should resolve this, if that's the case.
