### ISSUE TITLE
Relaxation of stake times

### ISSUE THREAD

**Issue by jagerman** [loki-project/loki#302]
Currently submitting a stake for a shared contribution service node locks the stake funds for 30 days; this can result in funds being locked for noticeably longer than the service node is itself registered.

For example: if a SN registered 48 hours ago receives a final contribution right now, the SN expired in 28 days but the final contributors' stake doesn't unlock for 30 days, i.e. 2 days longer than the SN itself.

A consequence of this is that contributors will be highly reluctant to contribute to service nodes that have been waiting longer periods because of extra lockup period with no SN reward earnings.

It would be nice for the network to allow stakes shorter than 30 days to be submitted so long as they are still >= the SN registration expiry, and for the wallet to get the registration/expiry time for a service node when submitting a stake and shorten the stake time accordingly.

**Comment by Doy-lee** [comment]
This sounds like a reasonable improvement, I can't think of any immediate down sides to this. @KeeJef

**Comment by KeeJef** [comment]
Yeah in agreement here that this would be a good change

**Comment by Doy-lee** [comment]
Non issue with Infinite Staking https://github.com/loki-project/loki/pull/406 since the time lock portion is removed. Stakes are now managed at a per block granularity.
