### ISSUE TITLE
Multiple autostakes on the same wallet don't work

### ISSUE THREAD

**Issue by MartinGHub** [loki-project/loki#333]
If you autostake multiple nodes on the same wallet client (e.g. running multiple "register_service_node auto" commands on the same wallet-cli) it will correctly spawn multiple wallet-cli processes and ran them in background, but only the first will actually autostake, the others will fail and nodes will get deregitered.

PS: I registered 4 nodes, each with 10 block delay after another

**Comment by Doy-lee** [comment]
This actually isn't allowed anymore in Festive Freya. The wallet now locks each wallet file so it can only be opened by 1 instance at a time.

See: https://github.com/monero-project/monero/pull/3994
