### ISSUE TITLE
Infinite Staking 

### ISSUE THREAD

**Issue by KeeJef** [loki-project/loki#346]
**This scheme should allow for staking without re-registration, while still allowing for two desirable properties.**

- Stakers that move funds are immediately have their Service Nodes deregistered  
- Service Nodes stakes that are deregistered for poor network behavior are locked for 30 days

**The Scheme should work as follows** 

1. Bob constructs a transaction sending the required full staking requirement to himself, inside the TX extra Bob exposes his TX Private key. Bob's outputs are also blacklisted from being used as mixins in other transactions. 
2.  Full Nodes and Service Nodes audit the amount of the transaction, if the amount is satisfactory Bob's 
Service Node is added to the Service Node list.
3. Full nodes and Service Nodes calculate the corresponding future Key Image for bob's transaction from his TX Private Key.

**After this one of two cases can occur**

1. If Bob spends the output contained in his stake then he will produce an identifiable Key Image, at this stage Full Nodes and Service Nodes can remove Bob's Node from the Service Node list. 

2. Bob's Service Node is deregistered for poor network performance, in this case his Key Image is locked for 30 days, any attempt to spend his previously staked outputs should be detected as an invalid TX input. After 30 days Bob's Key Image lock is removed an Bob can spend his outputs again.
 
The obvious tradeoff here is that this scheme does not allow participants to reduce their stake progressively, they must monitor the Staking Requirement and decide when to reduce their stake, however i think this trade off is accounted for by the decreased difficulty that the this scheme would provide. 

Credit to @jcktm and @Doy-lee for some of the ideas here

**Comment by jagerman** [comment]
> The obvious tradeoff here ...

There's a tradeoff on the flip side of this: there will be a strong incentive around block 1116383 to stake infinitely, thus effectively allowing SNs to forever avoid the stake increases starting there.

**Comment by Doy-lee** [comment]
With the network stability problem being able to jump out any time, how about having to submit a request to unlock your key image at your next expiry period? Where each expiry period is from the day the key image is locked `begin date + max(30 days, 30 * N months)`

**Comment by jcktm** [comment]
Implementation suggestion: stake for 30 days as usual, just don't expire if the funds haven't moved (i.e. if key image has not bee seen). then the only part to add is to expire when the key image appears, if it's after the expiration time.

**Comment by jagerman** [comment]
> Implementation suggestion: stake for 30 days as usual, just don't expire if the funds haven't moved (i.e. if key image has not bee seen).

Balance verification via unspent key images is not a pleasant thing to do; to keep the list entirely consistent across the network you'd have to check every stake key image (up to 4 per SN) on every new block to make sure it wasn't spent in that new block.

There is also the problem that, after 30 days, you'd be entering an indefinite period when there isn't any penalty to bad behaviour, which currently only has a short, finite window (i.e. between your last payment block and registration expiry block).

**Comment by Doy-lee** [comment]
Implemented in https://github.com/loki-project/loki/pull/406

Currently there is a maximum of 4 locked key images per node that transactions must be checked against. Time lock is removed and locking is enforced in the service node layer instead of the transaction layer.

Bad behaviour is punished by 30 days of lock at time of deregistration. Voluntarily unlocking, keeps the transaction locked for half the duration of a deregistration at the time it is requested and unlocks all stakes associated with the node.
