### ISSUE TITLE
lokid as a Service

### ISSUE THREAD

**Issue by KeeJef** [loki-project/loki#347]
Ideally the lokid daemon should run as a Service, by having this as the default option on Debian based systems we would prevent many of the issues caused by unintended screen closures, it would also streamline the install process

**Comment by majestrate** [comment]
This is the systemd unit i use on my seed node.
```
[Unit]
Description=lokid coin thingydoo hicky
Wants=network.target
After=network.target

[Service]
type=simple
User=loki
ExecStart=/usr/local/bin/lokid --no-igd --non-interactive
Restart=always

[Install]
WantedBy=multi-user.target
```

**Comment by jagerman** [comment]
`Wants/After=network.target` there should be `Wants/After=network-online.target` (see https://www.freedesktop.org/wiki/Software/systemd/NetworkTarget/).

**Comment by jagerman** [comment]
#367 will also make this a lot more convenient.

**Comment by jagerman** [comment]
https://github.com/loki-project/loki-docs/pull/46 addressed this in the documentation by putting it front and centre (instead of screen).

**Comment by KeeJef** [comment]
If we are going to switch everything over we should probably include the run as Service script in the release, or intercept some custom flag like `lokid --service-node --service` and run as a service

**Comment by majestrate** [comment]
On Wed, Mar 06, 2019 at 10:41:58PM -0800, Kee Jefferys wrote:
> If we are going to switch everything over we should probably include the run as Service script in the release, or intercept some custom flag like `lokid --service-node --service` and run as a service

doing that would make loki hard depend on systemd which will probably piss off a lot of people.

**Comment by KeeJef** [comment]
> 
> On Wed, Mar 06, 2019 at 10:41:58PM -0800, Kee Jefferys wrote: If we are going to switch everything over we should probably include the run as Service script in the release, or intercept some custom flag like `lokid --service-node --service` and run as a service
> doing that would make loki hard depend on systemd which will probably piss off a lot of people.
> […](#)
> -- You are receiving this because you commented. Reply to this email directly or view it on GitHub: [#347 (comment)](https://github.com/loki-project/loki/issues/347#issuecomment-470405853)

Not suggesting that be default behavior, we could either bundle a script with the binaries or i think we could intercept a flag in this case --service or --run-as-service, you cant still run lokid --service-node inside a screen if you want.

**Comment by jagerman** [comment]
Really not a fan of `lokid` itself having code in it to deal with systemd.  Perhaps just a `install-as-systemd-service.sh` script distributed with the binaries that copies the service file into place and activates it?

**Comment by KeeJef** [comment]
Yeah distributing a script is probably the way to go, we should just tell people to use the script in the guide if they are planning on running a SNODE

**Comment by majestrate** [comment]
On Thu, Mar 07, 2019 at 06:44:31AM -0800, Kee Jefferys wrote:
> Yeah distributing a script is probably the way to go, we should just tell people to use the script in the guide if they are planning on running a SNODE

init scripts are the responsibility of the package maintainer, who is in charge of that right now?

**Comment by KeeJef** [comment]
This is largely solved by the new Service Node staking guide which only shows the user how to run their Service Node as a Service, the Loki launcher will further manage lokid when released
