### ISSUE TITLE
libgcc_s_seh-1.dll error

### ISSUE THREAD

**Issue by BYOUNGSIKCHUN** [loki-project/loki#365]
Clicking executable after installing wallet causes the following error
![default](https://user-images.githubusercontent.com/39573139/49458529-5603ac00-f830-11e8-9a2f-73d1226d5b39.JPG)

window7 x64 user

**Comment by Doy-lee** [comment]
This is fixed in the latest GUI binaries. See https://github.com/loki-project/loki/issues/364

Please try the newest uploaded binaries.

Thanks.
