### ISSUE TITLE
Add a check for current block & time before allowing prepare_registration

### ISSUE THREAD

**Issue by jagerman** [loki-project/loki#382]
A node operator on Telegram (username Cinderblocks if more info is needed) reported getting quickly desynced after registration: it turned out that the node was 2.0.0 and was stuck at the fork height.

I suggest that lokid should have a check both for the network before synched (or perhaps within the last few blocks) *and* that the last block it knows about has a recent timestamp (say, 1 hour) to catch possible desyncs like this one from happening.

**Comment by Doy-lee** [comment]
Should be addresses in references PR.
