### ISSUE TITLE
The application “loki-wallet-gui.app” can’t be opened on OSX (loki-gui-osx-x64-2.0.2)

### ISSUE THREAD

**Issue by hiwebhq** [loki-project/loki#384]
Help - Recently having issues with Mac OSX Loki Client.

Error: The application “loki-wallet-gui.app” can’t be opened.  *Unable to run application.

Tried loading on a second OSX box with same issue.

OSC Version: 10.14.2
Loki Client: loki-gui-osx-x64-2.0.2

Please help?

**Comment by hiwebhq** [comment]
UPDATE:   

loki-gui-osx-x64-2.0.2 - I get the "The application “loki-wallet-gui.app” can’t be opened." Error
loki-gui-osx-x64-2.0.1 - This version opens and runs as desired....   

Please advise on why the new version will not RUN?

Thanks

**Comment by msgmaxim** [comment]
It seems that there are some problems with the dynamic libraries included in the executable. If you replace the contents of loki-wallet-gui.app/Contents/Resources/qml with that from the previous working version (2.0.1), it should work. I will fix the build and update the binaries shortly.

**Comment by hiwebhq** [comment]
I renamed current loki-wallet-gui.app/Contents/Resources/qml to loki-wallet-gui.app/Contents/Resources/qml.old and then copied loki-wallet-gui.app/Contents/Resources/qml  from the v2.0.1 and same error.   Please advise?

**Comment by hiwebhq** [comment]
That worked, along with need to set +x on the 'lokid' for the daemon to start.   ---   Thanks for your support -  Q: So what is this happen in a critical moment?    How can this issue be avoided in the future?   How can I help?      -   Id like to continue Loki-Project support!    #hiweb

**Comment by hiwebhq** [comment]
Closing issue as resolved......

**Comment by msgmaxim** [comment]
Thanks for providing feedback! We will keep improving our build script to minimise issues like that in the future. You can help us by reporting any further bugs :)
