### ISSUE TITLE
Block 14246 Lokid Crash

### ISSUE THREAD

**Issue by jpthor** [loki-project/loki#399]
Observed on Linux V2.0.2 and V2.0.3 

Lokid exits with "killed" on block 14246 from a clean start. A restart of the demon fixes. 
Lokid was running in service-node mode. 

Ubuntu 16.04.5 x64
1gb Ram/25gb SSD

**Comment by Doy-lee** [comment]
I suspect this is an out of memory issue, particularly if the killed message was dropped in the terminal. Does the computer have some swap space setup?

https://www.digitalocean.com/community/tutorials/how-to-add-swap-space-on-ubuntu-16-04
