### ISSUE TITLE
Magic Mani 1.0.4  LOKI

### ISSUE THREAD

**Issue by JHong111** [loki-project/loki#400]
I received some loki when I used Magic Mani 1.0.4. The height of these loki is after 161849. He is not in Festive Freya 2.0.3. What are these loki coins, is it valuable? Where can I use it? please help me

**Comment by Doy-lee** [comment]
Possibly on a split chain for miners mining on 1.0.4 after the fork height. You may load up your wallet and use show_transfers to locate the transfers after 161849 and check the TXID's on a block explorer like, explorer.loki-pool.com or lokiblocks.com

**Comment by Doy-lee** [comment]
Unlikely you will need to get a majority to recognise the payments on that Blockchain. Unfortunately there is due diligence required to stay on top of the network and potential forks like this. A good indicator could be if you suddenly start receiving payments more or less frequently than expected according to calculators and whatnot- but also just keeping an eye through various communication channels from your pool of choice or Loki's channels (Telegram and Discord).

**Comment by jagerman** [comment]
Loki had a mandatory network upgrade which changed the Loki blockchain rules starting at block 161849, which was widely announced on all Loki's media (https://loki.network/festive-freya-announcement/).  This will not be the last mandatory network upgrade--such upgrades are necessary to add new features and parameters to the loki network.

As for forking, Loki is the chain as determined by the Loki team and community.  A chain that shares a history with Loki but stops following Loki rules can be created at any point--in this case, by old Loki versions that don't know about the new consensus rules.  Any such chain following old rules beyond block 161849 (or, really, any other block) is not Loki, it is a forked coin that shares a history (up to block 161848) with Loki.  Someone *could* technically pick up such an alternate chain, name it, mine it, and turn it into their own coin and community, but it is not Loki, and (as far as I know) no one has done this.
