### ISSUE TITLE
Delayed Transaction Submission system

### ISSUE THREAD

**Issue by KeeJef** [loki-project/loki#463]
Time Correlation attacks are attacks where a users connection or submission of data is correlated with known identities actions. For example if Alice always connects to a remote node in the Loki network and shortly after a compromised party Eve receives a transaction then we can draw a correlation between the two users, this correlation gets stronger the more the two events occur within the same time period. 

To break this link in Loki delayed transactions should be introduced, The idea here is that we should give the ability for users to send special transactions to Service Nodes for storage, the Service Node should hold this transaction and then submit it to the Loki network once the specified TTL was reached.

To prevent DoS attacks on Service Nodes by filling them with transactions anti-spam measures can be introduced by limiting the TTL on each transaction, Service Nodes can also limit their stored transactions by rate limiting per IP or requiring addition of some short PoW for stored TX’s.

If a full PoS system was created, transactions could be delayed without any additional rate limiting as the Service Node who stored them would be able to claim the transaction fees associated with the transaction.

Through the addition of delayed TX’s plausible deniability can be applied over the whole transaction set, as an observer cannot use the fact that you connected to a remote node or the Loki network as the basis for its correlation to a specific transaction since the transaction could have been submitted while you maintained no connection to the network.

**Comment by Doy-lee** [comment]
For clarification, is the reason this is best done on the Service Node and not TTL on transactions sitting in the TX pool is to remove linkability between the client and their remote node, because it doesn't appear publicly in the transaction pool until it's been submitted by the Service Node?

And that if it were done as TTL in the transaction pool, you can make a link between the two by tracking when Alice connected, the state of the transaction pool, and comparing the state of the transaction pool when Eve gets credited?

**Comment by KeeJef** [comment]
Yes that is one reason, there are a few more. 

Instead of burdening every Service Node and full node with holding these long TTL transactions in their mempool we only require a single node to hold the extra data. 

And, Putting delayed TX's into the mempool removes the plausible deniability on non delayed transactions since anyone observing the mempool can easily create a historical list of transactions that were delayed. If the transaction is instead sent to a remote node/Service Node there is no distinguishing quality between that transaction and any other non delayed transaction, which means any transaction could have plausibly been created at any time, and only submitted to the network later.

**Comment by fireice-uk** [comment]
Not sure where you prefer to discuss, so I will re-post reddit comment here:

> One thing that you should note before implementing that system - transaction fee as per Monero implementation will leak timing data  on the state of the blockchain rendering the whole exercise pointless.

Simplest fix is to move to a fixed fee.

**Comment by KeeJef** [comment]
After some thought, not sure how possible this is, it seems you would also leak timing via your output selection, since transactions select not via random distribution but by sampling a spend distribution, selecting outputs closer to the date of the TX creation.
