### ISSUE TITLE
Loki and scaling

### ISSUE THREAD

**Issue by soum1234** [loki-project/loki#468]
H i 

i have deployed loki in my kubernetes cluster.
currently it has loki server, promtail and grafana.The log size which i get daily from all the pods in the kubernetes cluster is very huge.how do i scale the loki pods,If i add more no of replicas then how do i have the same data on all the pods  so that grafana can show it in the UI all the data present.
should i use a nfs volume for that?
or do i need to do an increase of the disk size whenecer the size is almost full

thanks

**Comment by Doy-lee** [comment]
See: https://github.com/loki-project/loki/issues/470#issuecomment-471150359
