### ISSUE TITLE
Loki  server - query the data of boltdb

### ISSUE THREAD

**Issue by soum1234** [loki-project/loki#469]
hi 

i have loki server,loki-promtail and loki-grafana pods running in my kubernetes cluster
can i enter into the loki server pod and do a query on the data.in loki i have the chunks and indexes but i do not know how to query the data inside the loki server using the boltdb queries.
pls provide the queries or any documentation of boltdb

thanks

**Comment by Doy-lee** [comment]
Sorry is this question asking how to use a third party library to query inside the Loki DB? That'd depend on BoltDB's interoperability with LMDB and your best bet is to check BoltDB docs.

As for how Loki uses LMDB can be seen here: https://github.com/loki-project/loki/blob/master/src/blockchain_db/lmdb/db_lmdb.cpp
