### ISSUE TITLE
loki - grafana UI

### ISSUE THREAD

**Issue by soum1234** [loki-project/loki#470]
In the loki-grafana ui , can i get the count of no of occurences of a particular search string also is there any possibility of increasing the no of records that are output by the search (currently it is only 1000) but there may be huge no of records.
also is there any possibility of downloading the  search data from the grafana UI to the local machine 

thanks  in advance for answering

**Comment by Doy-lee** [comment]
I suspect you are looking for information about: https://grafana.com/loki#about this is the Github for https://loki.network which is a different product.
