### ISSUE TITLE
Duplicate address in mainnet seeds

### ISSUE THREAD

**Issue by jagerman** [loki-project/loki#473]
In `net_node.inl`:
```
        full_addrs.insert("162.208.9.194:22022");  // Simon's spare
        full_addrs.insert("162.208.9.194:22022");  // OVH(1) is bae
```
I assume it's a copy and paste error (both were added at the same time), and the IP doesn't appear to be an OVH IP so I suspect the second one is incorrect here.

**Comment by KeeJef** [comment]
@Haafingar

**Comment by Haafingar** [comment]
I thought this was corrected but I guess not. I will do a new PR updating this. Anyone want to include seed nodes?

**Comment by KeeJef** [comment]
Fixed here https://github.com/loki-project/loki/commit/a362aa74c23658609d1d4be0a14e4a391cbe6230
