### ISSUE TITLE
Sweep_all  subaddresses

### ISSUE THREAD

**Issue by Azazel020** [loki-project/loki#494]

**Comment by Azazel020** [comment]
I have created several sub addresses in the CLI-wallet. I receive transactions on all those addresses but when I want to register my service node I get a sweep_all notification. I executed this command and after a 10 block conformation I tried again. But again the sweep_all notification...it looks like it does the sweep_all 1 address at the time. I had 4 addresses and had to do the sweep all 4 times before I could register my service node.

**Comment by Doy-lee** [comment]
You can select multiple addresses using the `[index=<N1>[,<N2>,...]]` option of the command, i.e. `sweep_all index=0,1,2,3` to target the primary address and the subsequent 3 subaddresses.

See: `help sweep_all` for more information in the wallet CLI.
