### ISSUE TITLE
Service Node deregistered with no real warning on windows console

### ISSUE THREAD

**Issue by MetallianFR68** [loki-project/loki#551]
I have to share my bad experience with the windows build.
I was running a supernode for 3 days.
After day 3, it was suddenly unregistered.
The attached log file seems very strange to me.
During 24 hours, the console continued to send "proof of life" quite often.
It's only when I restarted the process because I didn't get any more block reward that an error message appeared saying that the node was unregistered.

This was very confusing.
Now my stake is locked for 30 days and I'm very sorry about that.

I was running on a top notch machine, with high bandwidth connection (200Mb/200mb), backup connection and backup battery.

I think that the console log should be more explicit.
I also think that the penalty of the stake beeing locked for 30 days is way to much.

[lokid.txt](https://github.com/loki-project/loki-network/files/3041238/lokid.txt)

**Comment by Patrickdurbin** [comment]
Recommend Running your compile on testnet to see if same issue presents on a windows machine on a VPS!

**Comment by Doy-lee** [comment]
Please start a new issue if you wish to discuss stake lock time. As for warnings, new logs are in place for notifying when your proof is received back from the network in tandem with proof being sent out. This provides some more diagnostics in the case where you are connected to no peers and broadcast your proof to no one (shouting in the forest, so to speak).

Added in: https://github.com/loki-project/loki/pull/845 #858 
Merged to master in: #883
