### ISSUE TITLE
Error: Reason: Verification failed, connection should be dropped, Double spend TX

### ISSUE THREAD

**Issue by netmebtc** [loki-project/loki#597]
My wallet cannot transfer any coin out
OS:ubuntu16.04 ,windows10
wallet ersion: 3.0.5 cli

when transfer coin in my wallet, then rejected by daemon.   daemon syncing normal and wallet re-created from seeds and rescan_bc.      When I change to use other wallet connect with the same node daemon  can transfer normal. 

========error log===========
[wallet L5Nx8a]: transfer L7z7......vtdd 10
Wallet password:*******
Transaction 1/1:
Spending from address index 0
Sending 10.000000000.  The transaction fee is 0.000549700
Is this okay? (Y/Yes/N/No): y
Error: transaction <6bbcf0238ca8a68dbe95b58c959a245f4f679b95290d8edaec22e4ae8803f203> was rejected by daemon
Error: Reason: Verification failed, connection should be dropped, Double spend TX

**Comment by netmebtc** [comment]
All transfers are done.

**Comment by Vamsidharkn68** [comment]
Hi netmbtc I am also facing the same issue can you pls help in that
