### ISSUE TITLE
Generating RPC registration commands should be restricted

### ISSUE THREAD

**Issue by jagerman** [loki-project/loki#609]
Currently an SN can be asked to generate a registration over restricted RPC, which isn't good (someone could find an inactive SN with a public RPC and use it for free SN hosting, at least until the admin notices).

https://github.com/loki-project/loki/blob/27bc2aa11dd3fbee27537783cbeeaf8b1377f58e/src/rpc/core_rpc_server.h#L167

as well as the raw version:

https://github.com/loki-project/loki/blob/27bc2aa11dd3fbee27537783cbeeaf8b1377f58e/src/rpc/core_rpc_server.h#L165

**Comment by Doy-lee** [comment]
Addressed in #658
