### ISSUE TITLE
Incorporate public IP addresses of Service Nodes into uptime proofs.

### ISSUE THREAD

**Issue by msgmaxim** [loki-project/loki#617]
Service Nodes will be required to pass in their publicly reachable IP addresses via a command line option (set either manually or by Loki Launcher). These IPs will be available via `get_service_node_list` RPC alongside their respective snode public keys. This is necessary to for the messenger to work in absence of lokinet.

**Comment by jagerman** [comment]
It will need to include the port, too, and might need IP:port entries for multiple services eventually (just storage server initially, but we'll likely need other ports--such as the lokid rpc port--in the future).

**Comment by msgmaxim** [comment]
Done in #622.
