### ISSUE TITLE
Backup service nodes

### ISSUE THREAD

**Issue by jagerman** [loki-project/loki#633]
Many service node operators run two servers for the same service node, and advertise this when looking for contributors, for example a recent SN advertisement included:

> Service node are hosted on 2 different VPS (redundant setup) from 2 different providers

What people have been doing is simply running two different SNs with `--service-node` but the same `~/.loki/key` file.  If you watch what actually happens with this setup you effectively get a race condition between the two SN on which one sends out the uptime proof; depending on the precise timing of the internal sleeping you can have one that is consistently master for a while, then switches completely for a while.  Or you can get flip flops on every announces.

This is a problem starting in 4.0.0 because of the inclusion of the SN IP: every time the server sending the uptime proof "wins" it changes the IP on which the network tries to reach the SN's storage server, and of course, the backup won't have files just stashed with the storage server.

The problem will get worse in the future with blink and other quorum communication, and with lokinet routing.

I propose that initially we add a `--backup-service-node` option that uses slightly different rules for uptime proofs: it would wait longer (70 minutes) before sending an uptime proof (both after startup and after the last observed proof).  Thus as long as the master node is sending them every 60 minutes, the backup node would rarely actually send any, which should result in a much more consistent SN-to-IP mapping.

**Comment by jagerman** [comment]
In theory we should instead prefer that people just use higher reliability VPSes, but I think that that ship has already sailed.

**Comment by yidakee** [comment]
@jagerman - It's an incentives game. The backup servers exist because of the high penalty for downtime. If an analogous penalty is enforced to punish "same key different IP", SN ops will quickly adapt. Also, master SN could also have option to directly ping slave node to reduce network chatter, and failing to receive uptime, server gets elevated to master.

**Comment by neuroscr** [comment]
@majestrate says lokinet can't support dual nodes sharing a key at all. So maybe now is the time to deprecate this practice.

**Comment by jagerman** [comment]
@neuroscr - the point is to make multiple nodes not share an IP; this fallback would only kick in if the primary node misses an announce and thus is probably down.

**Comment by majestrate** [comment]
On Sat, Jun 08, 2019 at 07:09:55AM -0700, Jason Rhinelander wrote:
> @neuroscr - the point is to make multiple nodes not share an IP; this fallback would only kick in if the primary node misses an announce and thus is probably down.

this is effectively a failover mechanism for lokid service nodes right?

**Comment by jagerman** [comment]
@yidakee - I quite like that idea.  Rather than changing the punishment for dropping out (#604), we could punish them each time they change their announced IP by shoving them to the back of the reward list.  This would still require some quorum work -- quorums would need to keep track of announced IPs an submit a "bump position" transaction when you change IPs -- but would align incentives better between the network well-being (for which changing IPs is bad) and service node operator incentives.

**Comment by Doy-lee** [comment]
The big thing here is that it breaks interaction with storage server- so it'd be more fruitful for now to relax the deregistration process.

Haafingar's idea mentioned in offline discussion of multiple service nodes in the registration seems like the best idea so far and where we should be spending engineering time to allowing backup service nodes.

It could be as simple as allowing up to N service nodes per registration, they all route unique data, store their own set of unique storage server data and we just aggregate uptime/analytics from all the service nodes marked in the registration before deciding if we should completely deregister it.

**Comment by jagerman** [comment]
> It could be as simple as allowing up to N service nodes per registration ...

That is not so simple: it would require everyone to re-register, at a minimum.  It doesn't appear to entirely solve the issue: as an operator, it would still be just fine for me to just continue to broadcast multiple IPs because there's no incentive not to.  Running two full service nodes that fully route data all the time increases my costs with no matching increase in incentive.

**Comment by jagerman** [comment]
> It could be as simple as allowing up to N service nodes per registration

There's another potential problem with this: it weakens the security you get from random sampling for quorum building.  So we'd have to adjust quorum selection to select random fromly stakes, rather than from service node keys.  That's possible, of course, but adds further complications.

**Comment by msgmaxim** [comment]
> It could be as simple as allowing up to N service nodes per registration

The whole idea about uptime proofs is to demonstrate that the Service Node operator provides required services like the storage server. If we allow multiple instances, we change that to "at least one service (storage/daemon pair) is running", which is not great at all. I could then register a snode with 10 service node keys and have only 1 of them actually used in a daemon/storage setup, but the network would have no idea.

Some time in the future we are going to enforce storage testing, and we will get back to the initial problem of operators wanting backups for each of their daemon/storage pairs...

**Comment by jagerman** [comment]
In the interest of time (we have only about 2 weeks before the scheduled 4.0.0 testnet RC release) I really think we should keep this simple *for now* and come back to a more sophisticated approach later.

Here are some relatively simple approaches we could use:

1) #604 relaxations so that running a backup node isn't important anymore -- if operators have 24 hours to fix a problem (during which they would be ineligible for rewards, would stop being part of quorum selection, etc., and would start back at the bottom of the list when they come back -- or get permanently deregistered if they go 24 hours) then we seriously reduce the need for a backup server in the first place.  We can then also ask SN operators to please stop running backup servers.

2) Add a `--backup` flag that uses longer (Maybe 1h10m?  1h30m?  1h50m?) times since the last uptime proof.

3) #2 plus incentives: every time a quorum detects that your IP changes you get bumped to the back of the service node reward list.  This gives operators a strong incentive to actually *use* the `--backup` flag and should result in backups very rarely actually making it on the network.

I'm kind of leaning towards liking #1 for now.  Once we have storage server testing implemented we can think about how that plays in with the concept of backup nodes.

**Comment by Doy-lee** [comment]
@msgmaxim This would be addressed by they all route their own data since they have their own key- they are responsible for whatever data is destined for it but collectively your stake is not blacklisted if we determine your service is still satisfactorily running across the N service nodes setup.

Multiple IPs will fail in the future because of storage tests. Not going to be mitigated in 4.0.0 sure.

The amount of complication this adds is worth deciding if we can somehow just flat out prevent, or prevent the need for people to use backups in the first place.

-- Edit
Relaxation will be sufficient for the majority of cases.

**Comment by msgmaxim** [comment]
@Doy-lee I'm just saying that backup nodes should *not* compliment each other, but rather provide redundancy. I is responsibility of SN operators to forward requests or do whatever necessary to provide Loki services with redundancy (but we could perhaps help with that in the future).

@jagerman I know we are limited in time, but it sounds like 1 and 3 together provide a very robust solution (and I suspect once 1 is implemented, 3 should not be too difficult to add).

**Comment by Fez29** [comment]
I like Option 1 as a start but having the ability to have backup nodes would be awesome and would also surely strengthen the network in the sense that if there was a large VPS provider datacentre affected by a complete outage alot of those Service Nodes would be able to recover to their backup nodes.

Mirroring the storage on the main node to the --backup node by having an option to connect to the master node from the backup node and replicate the data directly could also be helpful. If it doesnt present major work and/or could have security concerns.

**Comment by Doy-lee** [comment]
Closed. The goal of redundancy in servers was addressed in relaxing deregistration with the new crediting system. At this point in time introducing 2 methods of redundancy (multiple ip support for backup servers AND credits) is not in our interest. 

See https://github.com/loki-project/loki/issues/604 for more information on the new crediting system.
