### ISSUE TITLE
Add stake unlock time to CLI for deregistered SN

### ISSUE THREAD

**Issue by cryptolokimax** [loki-project/loki#634]
Suggestion from http://t.me/Abhijith_15d 

Could you please include a feature in the cli to know when the locked stake will unlock if my node expires, some of my nodes expired when I was on a holiday.

I'm finding it very difficult to know when it'll get unlocked.. I tried looking at the lokid but I couldn't find at what block height it got expired.

It'll be really useful to know when, for now I'm checking twice each day as it has roughly been around 30 days without rewards.

**Comment by minethio** [comment]
@cryptolokimax if you issue `print_locked_stakes` from the staking wallet, you can find out the block height your funds will unlock:
```
[wallet LCEif5 (has locked stakes)]: print_locked_stakes
Wallet password: 
Service Node: <SERVICE_NODE_PUBLIC_KEY>
Unlock Height: Unlock not requested yet
Total Locked: <UNLOCKED_BLANACE>
Amount/Key Image: <BALANCE>/<KEY>
```
The unlock height is obviously what you are looking for.
