### ISSUE TITLE
premine not showing up in new fork

### ISSUE THREAD

**Issue by LeoCornelius** [loki-project/loki#635]
i forked loki and got the new genesis hash with the old branch on your repo and edited the premine amount and i have mined a few blocks but even after resyncing the wallet multiple times from 0 the premine is not showing up . The daemon confirms it is in the network https://cdn.discordapp.com/attachments/479323606241771521/587400496927735808/unknown.png but it does not show up inwallet. I am sorry if this is not the correct place to open this issue. here is the github repo: https://github.com/kegcoin-project/kegcoin ;) thanks

**Comment by Doy-lee** [comment]
You need wallet code to support reading the genesis block since there are some optimisations to exclude blocks that are too old time-wise.

The basic gist can be found in my ConsensusNet branch or the original patch is available here: https://loki.network/2018/05/16/loki-premine-report/

**Comment by LeoCornelius** [comment]
thanks! will check it out
