### ISSUE TITLE
cmake error

### ISSUE THREAD

**Issue by freebet** [loki-project/loki#64]
Determining if the pthread_create exist failed with the following output:
Change Dir: /usr/local/src/loki/build/release/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_b4bef/fast"
make[1]: Entering directory '/usr/local/src/loki/build/release/CMakeFiles/CMakeTmp'
/usr/bin/make -f CMakeFiles/cmTC_b4bef.dir/build.make CMakeFiles/cmTC_b4bef.dir/build
make[2]: Entering directory '/usr/local/src/loki/build/release/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_b4bef.dir/CheckSymbolExists.c.o
/usr/bin/cc     -o CMakeFiles/cmTC_b4bef.dir/CheckSymbolExists.c.o   -c /usr/local/src/loki/build/release/CMakeFiles/CMakeTmp/CheckSymbolExists.c
Linking C executable cmTC_b4bef
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_b4bef.dir/link.txt --verbose=1
/usr/bin/cc       CMakeFiles/cmTC_b4bef.dir/CheckSymbolExists.c.o  -o cmTC_b4bef -rdynamic 
CMakeFiles/cmTC_b4bef.dir/CheckSymbolExists.c.o: In function `main':
CheckSymbolExists.c:(.text+0x16): undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_b4bef.dir/build.make:97: recipe for target 'cmTC_b4bef' failed
make[2]: *** [cmTC_b4bef] Error 1
make[2]: Leaving directory '/usr/local/src/loki/build/release/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_b4bef/fast' failed
make[1]: *** [cmTC_b4bef/fast] Error 2
make[1]: Leaving directory '/usr/local/src/loki/build/release/CMakeFiles/CMakeTmp'

File /usr/local/src/loki/build/release/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <pthread.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef pthread_create
  return ((int*)(&pthread_create))[argc];
#else
  (void)argc;
  return 0;
#endif
}

Determining if the function memset_s exists in the c failed with the following output:
Change Dir: /usr/local/src/loki/build/release/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_930bb/fast"
make[1]: Entering directory '/usr/local/src/loki/build/release/CMakeFiles/CMakeTmp'
/usr/bin/make -f CMakeFiles/cmTC_930bb.dir/build.make CMakeFiles/cmTC_930bb.dir/build
make[2]: Entering directory '/usr/local/src/loki/build/release/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_930bb.dir/CheckFunctionExists.c.o
/usr/bin/cc    -DCHECK_FUNCTION_EXISTS=memset_s   -o CMakeFiles/cmTC_930bb.dir/CheckFunctionExists.c.o   -c /usr/share/cmake-3.5/Modules/CheckFunctionExists.c
Linking C executable cmTC_930bb
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_930bb.dir/link.txt --verbose=1
/usr/bin/cc   -DCHECK_FUNCTION_EXISTS=memset_s    CMakeFiles/cmTC_930bb.dir/CheckFunctionExists.c.o  -o cmTC_930bb  -L/usr/local/src/loki/build/release/CMakeFiles/CMakeTmp/string.h -rdynamic -lc -Wl,-rpath,/usr/local/src/loki/build/release/CMakeFiles/CMakeTmp/string.h 
CMakeFiles/cmTC_930bb.dir/CheckFunctionExists.c.o: In function `main':
CheckFunctionExists.c:(.text+0x15): undefined reference to `memset_s'
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_930bb.dir/build.make:97: recipe for target 'cmTC_930bb' failed
make[2]: *** [cmTC_930bb] Error 1
make[2]: Leaving directory '/usr/local/src/loki/build/release/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_930bb/fast' failed
make[1]: *** [cmTC_930bb/fast] Error 2
make[1]: Leaving directory '/usr/local/src/loki/build/release/CMakeFiles/CMakeTmp'

Determining if the function explicit_bzero exists in the c failed with the following output:
Change Dir: /usr/local/src/loki/build/release/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_0213d/fast"
make[1]: Entering directory '/usr/local/src/loki/build/release/CMakeFiles/CMakeTmp'
/usr/bin/make -f CMakeFiles/cmTC_0213d.dir/build.make CMakeFiles/cmTC_0213d.dir/build
make[2]: Entering directory '/usr/local/src/loki/build/release/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_0213d.dir/CheckFunctionExists.c.o
/usr/bin/cc    -DCHECK_FUNCTION_EXISTS=explicit_bzero   -o CMakeFiles/cmTC_0213d.dir/CheckFunctionExists.c.o   -c /usr/share/cmake-3.5/Modules/CheckFunctionExists.c
Linking C executable cmTC_0213d
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_0213d.dir/link.txt --verbose=1
/usr/bin/cc   -DCHECK_FUNCTION_EXISTS=explicit_bzero    CMakeFiles/cmTC_0213d.dir/CheckFunctionExists.c.o  -o cmTC_0213d  -L/usr/local/src/loki/build/release/CMakeFiles/CMakeTmp/strings.h -rdynamic -lc -Wl,-rpath,/usr/local/src/loki/build/release/CMakeFiles/CMakeTmp/strings.h 
CMakeFiles/cmTC_0213d.dir/CheckFunctionExists.c.o: In function `main':
CheckFunctionExists.c:(.text+0x15): undefined reference to `explicit_bzero'
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_0213d.dir/build.make:97: recipe for target 'cmTC_0213d' failed
make[2]: *** [cmTC_0213d] Error 1
make[2]: Leaving directory '/usr/local/src/loki/build/release/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_0213d/fast' failed
make[1]: *** [cmTC_0213d/fast] Error 2
make[1]: Leaving directory '/usr/local/src/loki/build/release/CMakeFiles/CMakeTmp'

Determining if the -Wl,-z,noexecheap linker flag is suppored failed with the following output:
Change Dir: /usr/local/src/loki/build/release/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_0350c/fast"
make[1]: Entering directory '/usr/local/src/loki/build/release/CMakeFiles/CMakeTmp'
/usr/bin/make -f CMakeFiles/cmTC_0350c.dir/build.make CMakeFiles/cmTC_0350c.dir/build
make[2]: Entering directory '/usr/local/src/loki/build/release/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_0350c.dir/CheckLinkerFlag.c.o
/usr/bin/cc    -Wl,-z,noexecheap    -Wl,-z,noexecheap -o CMakeFiles/cmTC_0350c.dir/CheckLinkerFlag.c.o   -c /usr/local/src/loki/cmake/CheckLinkerFlag.c
Linking C executable cmTC_0350c
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_0350c.dir/link.txt --verbose=1
/usr/bin/cc  -Wl,-z,noexecheap     CMakeFiles/cmTC_0350c.dir/CheckLinkerFlag.c.o  -o cmTC_0350c -rdynamic 
/usr/bin/ld: warning: -z noexecheap ignored.
make[2]: Leaving directory '/usr/local/src/loki/build/release/CMakeFiles/CMakeTmp'
make[1]: Leaving directory '/usr/local/src/loki/build/release/CMakeFiles/CMakeTmp'

Determining if the function rl_copy_text exists failed with the following output:
Change Dir: /usr/local/src/loki/build/release/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_fd17c/fast"
make[1]: Entering directory '/usr/local/src/loki/build/release/CMakeFiles/CMakeTmp'
/usr/bin/make -f CMakeFiles/cmTC_fd17c.dir/build.make CMakeFiles/cmTC_fd17c.dir/build
make[2]: Entering directory '/usr/local/src/loki/build/release/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_fd17c.dir/CheckFunctionExists.c.o
/usr/bin/cc    -fno-strict-aliasing -maes -std=c11 -D_GNU_SOURCE   -Wall -Wextra -Wpointer-arith -Wundef -Wvla -Wwrite-strings -Wno-error=extra -Wno-error=deprecated-declarations -Wno-unused-parameter -Wno-unused-variable -Wno-error=unused-variable -Wno-error=undef -Wno-error=uninitialized -Wlogical-op -Wno-error=maybe-uninitialized -Wno-error=cpp -Waggregate-return -Wnested-externs -Wold-style-definition -Wstrict-prototypes -march=native  -fPIC  -Wformat -Wformat-security -fstack-protector -fstack-protector-strong -fno-strict-aliasing -DCHECK_FUNCTION_EXISTS=rl_copy_text   -o CMakeFiles/cmTC_fd17c.dir/CheckFunctionExists.c.o   -c /usr/share/cmake-3.5/Modules/CheckFunctionExists.c
/usr/share/cmake-3.5/Modules/CheckFunctionExists.c:6:1: warning: function declaration isnâ€™t a prototype [-Wstrict-prototypes]
 char CHECK_FUNCTION_EXISTS();
 ^
Linking C executable cmTC_fd17c
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_fd17c.dir/link.txt --verbose=1
/usr/bin/cc   -fno-strict-aliasing -maes -std=c11 -D_GNU_SOURCE   -Wall -Wextra -Wpointer-arith -Wundef -Wvla -Wwrite-strings -Wno-error=extra -Wno-error=deprecated-declarations -Wno-unused-parameter -Wno-unused-variable -Wno-error=unused-variable -Wno-error=undef -Wno-error=uninitialized -Wlogical-op -Wno-error=maybe-uninitialized -Wno-error=cpp -Waggregate-return -Wnested-externs -Wold-style-definition -Wstrict-prototypes -march=native  -fPIC  -Wformat -Wformat-security -fstack-protector -fstack-protector-strong -fno-strict-aliasing -DCHECK_FUNCTION_EXISTS=rl_copy_text    CMakeFiles/cmTC_fd17c.dir/CheckFunctionExists.c.o  -o cmTC_fd17c -rdynamic 
CMakeFiles/cmTC_fd17c.dir/CheckFunctionExists.c.o: In function `main':
CheckFunctionExists.c:(.text+0x15): undefined reference to `rl_copy_text'
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_fd17c.dir/build.make:97: recipe for target 'cmTC_fd17c' failed
make[2]: *** [cmTC_fd17c] Error 1
make[2]: Leaving directory '/usr/local/src/loki/build/release/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_fd17c/fast' failed
make[1]: *** [cmTC_fd17c/fast] Error 2
make[1]: Leaving directory '/usr/local/src/loki/build/release/CMakeFiles/CMakeTmp'

Determining if the function rl_filename_completion_function exists failed with the following output:
Change Dir: /usr/local/src/loki/build/release/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_5ef57/fast"
make[1]: Entering directory '/usr/local/src/loki/build/release/CMakeFiles/CMakeTmp'
/usr/bin/make -f CMakeFiles/cmTC_5ef57.dir/build.make CMakeFiles/cmTC_5ef57.dir/build
make[2]: Entering directory '/usr/local/src/loki/build/release/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_5ef57.dir/CheckFunctionExists.c.o
/usr/bin/cc    -fno-strict-aliasing -maes -std=c11 -D_GNU_SOURCE   -Wall -Wextra -Wpointer-arith -Wundef -Wvla -Wwrite-strings -Wno-error=extra -Wno-error=deprecated-declarations -Wno-unused-parameter -Wno-unused-variable -Wno-error=unused-variable -Wno-error=undef -Wno-error=uninitialized -Wlogical-op -Wno-error=maybe-uninitialized -Wno-error=cpp -Waggregate-return -Wnested-externs -Wold-style-definition -Wstrict-prototypes -march=native  -fPIC  -Wformat -Wformat-security -fstack-protector -fstack-protector-strong -fno-strict-aliasing -DCHECK_FUNCTION_EXISTS=rl_filename_completion_function   -o CMakeFiles/cmTC_5ef57.dir/CheckFunctionExists.c.o   -c /usr/share/cmake-3.5/Modules/CheckFunctionExists.c
/usr/share/cmake-3.5/Modules/CheckFunctionExists.c:6:1: warning: function declaration isnâ€™t a prototype [-Wstrict-prototypes]
 char CHECK_FUNCTION_EXISTS();
 ^
Linking C executable cmTC_5ef57
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_5ef57.dir/link.txt --verbose=1
/usr/bin/cc   -fno-strict-aliasing -maes -std=c11 -D_GNU_SOURCE   -Wall -Wextra -Wpointer-arith -Wundef -Wvla -Wwrite-strings -Wno-error=extra -Wno-error=deprecated-declarations -Wno-unused-parameter -Wno-unused-variable -Wno-error=unused-variable -Wno-error=undef -Wno-error=uninitialized -Wlogical-op -Wno-error=maybe-uninitialized -Wno-error=cpp -Waggregate-return -Wnested-externs -Wold-style-definition -Wstrict-prototypes -march=native  -fPIC  -Wformat -Wformat-security -fstack-protector -fstack-protector-strong -fno-strict-aliasing -DCHECK_FUNCTION_EXISTS=rl_filename_completion_function    CMakeFiles/cmTC_5ef57.dir/CheckFunctionExists.c.o  -o cmTC_5ef57 -rdynamic 
CMakeFiles/cmTC_5ef57.dir/CheckFunctionExists.c.o: In function `main':
CheckFunctionExists.c:(.text+0x15): undefined reference to `rl_filename_completion_function'
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_5ef57.dir/build.make:97: recipe for target 'cmTC_5ef57' failed
make[2]: *** [cmTC_5ef57] Error 1
make[2]: Leaving directory '/usr/local/src/loki/build/release/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_5ef57/fast' failed
make[1]: *** [cmTC_5ef57/fast] Error 2
make[1]: Leaving directory '/usr/local/src/loki/build/release/CMakeFiles/CMakeTmp'

Determining if the function rl_copy_text exists failed with the following output:
Change Dir: /usr/local/src/loki/build/release/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_1e3b9/fast"
make[1]: Entering directory '/usr/local/src/loki/build/release/CMakeFiles/CMakeTmp'
/usr/bin/make -f CMakeFiles/cmTC_1e3b9.dir/build.make CMakeFiles/cmTC_1e3b9.dir/build
make[2]: Entering directory '/usr/local/src/loki/build/release/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_1e3b9.dir/CheckFunctionExists.c.o
/usr/bin/cc    -fno-strict-aliasing -maes -std=c11 -D_GNU_SOURCE   -Wall -Wextra -Wpointer-arith -Wundef -Wvla -Wwrite-strings -Wno-error=extra -Wno-error=deprecated-declarations -Wno-unused-parameter -Wno-unused-variable -Wno-error=unused-variable -Wno-error=undef -Wno-error=uninitialized -Wlogical-op -Wno-error=maybe-uninitialized -Wno-error=cpp -Waggregate-return -Wnested-externs -Wold-style-definition -Wstrict-prototypes -march=native  -fPIC  -Wformat -Wformat-security -fstack-protector -fstack-protector-strong -fno-strict-aliasing -DCHECK_FUNCTION_EXISTS=rl_copy_text   -o CMakeFiles/cmTC_1e3b9.dir/CheckFunctionExists.c.o   -c /usr/share/cmake-3.5/Modules/CheckFunctionExists.c
/usr/share/cmake-3.5/Modules/CheckFunctionExists.c:6:1: warning: function declaration isnâ€™t a prototype [-Wstrict-prototypes]
 char CHECK_FUNCTION_EXISTS();
 ^
Linking C executable cmTC_1e3b9
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_1e3b9.dir/link.txt --verbose=1
/usr/bin/cc   -fno-strict-aliasing -maes -std=c11 -D_GNU_SOURCE   -Wall -Wextra -Wpointer-arith -Wundef -Wvla -Wwrite-strings -Wno-error=extra -Wno-error=deprecated-declarations -Wno-unused-parameter -Wno-unused-variable -Wno-error=unused-variable -Wno-error=undef -Wno-error=uninitialized -Wlogical-op -Wno-error=maybe-uninitialized -Wno-error=cpp -Waggregate-return -Wnested-externs -Wold-style-definition -Wstrict-prototypes -march=native  -fPIC  -Wformat -Wformat-security -fstack-protector -fstack-protector-strong -fno-strict-aliasing -DCHECK_FUNCTION_EXISTS=rl_copy_text    CMakeFiles/cmTC_1e3b9.dir/CheckFunctionExists.c.o  -o cmTC_1e3b9 -rdynamic 
CMakeFiles/cmTC_1e3b9.dir/CheckFunctionExists.c.o: In function `main':
CheckFunctionExists.c:(.text+0x15): undefined reference to `rl_copy_text'
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_1e3b9.dir/build.make:97: recipe for target 'cmTC_1e3b9' failed
make[2]: *** [cmTC_1e3b9] Error 1
make[2]: Leaving directory '/usr/local/src/loki/build/release/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_1e3b9/fast' failed
make[1]: *** [cmTC_1e3b9/fast] Error 2
make[1]: Leaving directory '/usr/local/src/loki/build/release/CMakeFiles/CMakeTmp'

Determining if the function rl_filename_completion_function exists failed with the following output:
Change Dir: /usr/local/src/loki/build/release/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_cb353/fast"
make[1]: Entering directory '/usr/local/src/loki/build/release/CMakeFiles/CMakeTmp'
/usr/bin/make -f CMakeFiles/cmTC_cb353.dir/build.make CMakeFiles/cmTC_cb353.dir/build
make[2]: Entering directory '/usr/local/src/loki/build/release/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_cb353.dir/CheckFunctionExists.c.o
/usr/bin/cc    -fno-strict-aliasing -maes -std=c11 -D_GNU_SOURCE   -Wall -Wextra -Wpointer-arith -Wundef -Wvla -Wwrite-strings -Wno-error=extra -Wno-error=deprecated-declarations -Wno-unused-parameter -Wno-unused-variable -Wno-error=unused-variable -Wno-error=undef -Wno-error=uninitialized -Wlogical-op -Wno-error=maybe-uninitialized -Wno-error=cpp -Waggregate-return -Wnested-externs -Wold-style-definition -Wstrict-prototypes -march=native  -fPIC  -Wformat -Wformat-security -fstack-protector -fstack-protector-strong -fno-strict-aliasing -DCHECK_FUNCTION_EXISTS=rl_filename_completion_function   -o CMakeFiles/cmTC_cb353.dir/CheckFunctionExists.c.o   -c /usr/share/cmake-3.5/Modules/CheckFunctionExists.c
/usr/share/cmake-3.5/Modules/CheckFunctionExists.c:6:1: warning: function declaration isnâ€™t a prototype [-Wstrict-prototypes]
 char CHECK_FUNCTION_EXISTS();
 ^
Linking C executable cmTC_cb353
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_cb353.dir/link.txt --verbose=1
/usr/bin/cc   -fno-strict-aliasing -maes -std=c11 -D_GNU_SOURCE   -Wall -Wextra -Wpointer-arith -Wundef -Wvla -Wwrite-strings -Wno-error=extra -Wno-error=deprecated-declarations -Wno-unused-parameter -Wno-unused-variable -Wno-error=unused-variable -Wno-error=undef -Wno-error=uninitialized -Wlogical-op -Wno-error=maybe-uninitialized -Wno-error=cpp -Waggregate-return -Wnested-externs -Wold-style-definition -Wstrict-prototypes -march=native  -fPIC  -Wformat -Wformat-security -fstack-protector -fstack-protector-strong -fno-strict-aliasing -DCHECK_FUNCTION_EXISTS=rl_filename_completion_function    CMakeFiles/cmTC_cb353.dir/CheckFunctionExists.c.o  -o cmTC_cb353 -rdynamic 
CMakeFiles/cmTC_cb353.dir/CheckFunctionExists.c.o: In function `main':
CheckFunctionExists.c:(.text+0x15): undefined reference to `rl_filename_completion_function'
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_cb353.dir/build.make:97: recipe for target 'cmTC_cb353' failed
make[2]: *** [cmTC_cb353] Error 1
make[2]: Leaving directory '/usr/local/src/loki/build/release/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_cb353/fast' failed
make[1]: *** [cmTC_cb353/fast] Error 2
make[1]: Leaving directory '/usr/local/src/loki/build/release/CMakeFiles/CMakeTmp'

are you idea? i cant install daemon on ubuntu 16.04

**Comment by 0xA01** [comment]
@freebet any solution?
