### ISSUE TITLE
Solutions to running lokid with GLIBC_2.18? -- /lib64/libc.so.6: version `GLIBC_2.18' not found

### ISSUE THREAD

**Issue by patoshii** [loki-project/loki#645]
My server is a bit dated and I can't update it with the latest GLIBC_2.18 as some of my applications require the older GLIBC version. 

When running lokid I get the following error:

> ./lokid: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by ./lokid)

Is there a way to precompile this GLIBC version into lokid? And how would one go about doing this? 

Whats another solution to this problem?

**Comment by michael-loki** [comment]
Building from source is probably your best bet here. 

Out of interest, what OS and version?

**Comment by patoshii** [comment]
centos7

**Comment by patoshii** [comment]
how do i build from source ?

**Comment by Doy-lee** [comment]
We don't have a guide centos readily available. You will have to find the equivalent packages from the dependencies table https://github.com/loki-project/loki#dependencies in whatever package manager you're using.

I did some googling and https://github.com/monero-project/monero/issues/2085 might get you 90% of the way there.
