### ISSUE TITLE
Proof of Reserve broken

### ISSUE THREAD

**Issue by tokerato** [loki-project/loki#646]
Login to main wallet / machine #1 / Ubuntu 16.04 / Loki-latest
Created signature file in 4 different ways:
1) get_reserve_proof all password
2) get_reserve_proof all 
3) get_reserve_proof amount password (i.e get_reserve_proof 4000 password)
4) get_reserve_proof amount (i.e get_reserve_proof 4000)

Copied signature file to machine #2 / Ubuntu 16.04 / Loki-latest
Chmod 777 signature_file
Login to view wallet via loki_wallet_cli (mirroring main wallet on machine #1)
Also tested on completely different wallet  via loki_wallet_cli
All attempts to check_reserve_proof <address> fail:

Error: Bad signature

**Comment by Doy-lee** [comment]
Fixed in #647
