### ISSUE TITLE
GUI wallet only allowing me to send 1 transaction every 20 minutes

### ISSUE THREAD

**Issue by Zappedone** [loki-project/loki#65]
After sending the first transaction, my entire balance locks and doesn't let me send another one for another 20 minutes

**Comment by Doy-lee** [comment]
This is currently in to guard against potentially submitting transactions on an alternate chain especially in the early days when the network hash rate is still volatile. The 20mins gives some assurance that the transaction has been submitted to the correct chain and not reorganised out of existence.
