### ISSUE TITLE
Set min. staking requirement to 20k Loki for a SN with possible step downs in future

### ISSUE THREAD

**Issue by CryptoFirefly** [loki-project/loki#654]
I would like to propose that the team reviews the Loki required for a Service Node. 

The current curve takes us all the way down to 15k, and as we now have infinite staking, we need to remember it may be hard/challenging to later increase the amount, as we do have a perpetual tail emission. 

Reason's for suggesting we stop at 20k instead of letting it go all the way to 15k
1. We have a tail emission and even at 20k Loki, we can have upto 840 SNs at the total supply of 42 million Loki. (Assuming 40% lock-up into SNs)
2. Loki price does play, even at ICO price, at 20k Loki its not very expensive for the operator to contribute the minimum 25%. At lower rates its already very cheap.
3. We will get to a stable state quicker and not have people needing to re-stake as staking requirements keep dropping.
4. The Operator with 5k Loki, has some skin in the game, at 3750 its far too low an amount and small amounts being locked up for the operator will make operators not have enough risk of lock-ups. 
5. The node count doesn't grow so big that the rewards are paid out far too infrequently. 
6. With 7.3 million of tail emission, even sticking to constant 40% lock-up into SNs, we shall add approx 150 new SN's each year perpetually. 

Lastly, once the min staking is fixed at 20k. The Loki foundation has the flexibility to lower the staking in steps if needed based on conditions such as Loki being priced very high making it very expensive for operators. Or the network demands higher number of nodes.
In such a scenario at every hard fork the foundation could propose to lower staking in steps, e.g. from 20k to 19k in a step drop. Which the operators can then re-register to lower their stakes per node. The step could also be smoother with drops of 500 Loki to have minimal impact. In any case the tail emission is always working in our favour of having higher number of nodes at a fixed % of locked-up for SNs.

**Comment by Azazel020** [comment]
Set the requirement on a min of 20K Loki, start with checkpointing and 90% POS

**Comment by CryptoFirefly** [comment]
> Set the requirement on a min of 20K Loki, start with checkpointing and 90% POS

Yeah, given one exchange, and may be other exchanges now also staking, the % of circulating supply into Nodes should touch near 50% in coming months. That should push us over 1000 nodes very soon.

Going to 15k, will make the nodes unprofitable as more nodes would be needed for the same % of circ supply being stakes. Or need larger Op fees.
