### ISSUE TITLE
GUI Kubuntu 18.04 not working

### ISSUE THREAD

**Issue by n00by1** [loki-project/loki#69]
Prebuild release:
```
./start-gui.sh ./loki-wallet-gui: error while loading shared libraries: VBoxOGLcrutil.so: cannot open shared object file: No such file or directory

```
When compiling from source:
```
/usr/bin/x86_64-linux-gnu-ld: impossibile trovare -lwallet_merged
/usr/bin/x86_64-linux-gnu-ld: impossibile trovare -lepee
/usr/bin/x86_64-linux-gnu-ld: impossibile trovare -leasylogging
/usr/bin/x86_64-linux-gnu-ld: impossibile trovare -llmdb
collect2: error: ld returned 1 exit status
Makefile:295: recipe for target 'release/bin/loki-wallet-gui' failed
make: *** [release/bin/loki-wallet-gui] Error 1
```

**Comment by Doy-lee** [comment]
Are you running through a VM? The VBoxOGLcrutil.so seems to suggest so, if you are, try installing the guest additions cd. The package is virtualbox-guest-additions-iso, you can also install through the Virtual Box interface by inserting the guest cd.

As for building from source, when building the GUI, it builds the daemon in the Loki submodule. Somewhere in the Loki build, it's failing and not generating the required libraries to link against in loki/libs. You will need to look in the logs earlier to see what's failing when building the daemon.

**Comment by n00by1** [comment]
Update: when trying the compiled version (last edited) 
`./loki-wallet-gui: error while loading shared libraries: libicui18n.so.52: cannot open shared object file: No such file or directory`

**Comment by Doy-lee** [comment]
I'll have a relook at why it's pulling in VBoxOGLcrutil.so for whatever reason.

With libicu, that's required by Qt as part of having unicode support. The package that lives under is libicu-dev. You need version 52 and can ensure that the package manager has it and is installable with, "apt search libicu"

**Comment by Doy-lee** [comment]
It might be of interest to try the build posted in https://github.com/loki-project/loki-gui/issues/7 where I've built the GUI natively, so it should not try to pull in VBoxOGLcrutil.so

**Comment by n00by1** [comment]
It is working actually! Thanks Doy-lee
