### ISSUE TITLE
windows gui wallet

### ISSUE THREAD

**Issue by JacobKerr** [loki-project/loki#70]
on both a physical windows 10 computer and a vm windows 7 the program crashes out before the screen where the language is selected. 
this is the error on the vm windows 7:
Faulting application name: loki-wallet-gui.exe, version: 0.0.0.0, time stamp: 0x5aea54ce
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x0000000000000000
Faulting process id: 0xd78
Faulting application start time: 0x01d3e70208f77a78
Faulting application path: C:\Users\Wallets\Desktop\Wallets\loki-gui-win64-v0.1.0\loki-wallet-gui.exe
Faulting module path: unknown
Report Id: 4eb1bfd6-52f5-11e8-9c76-fd969736166f

**Comment by Doy-lee** [comment]
Try the suggested fix in #60

**Comment by Doy-lee** [comment]
Closed because of no further leads.
