### ISSUE TITLE
Store or hard code upgradeable service node states

### ISSUE THREAD

**Issue by jagerman** [loki-project/loki#746]
Currently when we change the SN data (or when a long reorg occurs) we need to do a full rescan, which can take nearly an hour.  This is only getting worse as the blockchain grows.

We should store some restorable version of the SN list once in a while so that restoration can begin from a later point.  A node could put this into the lmdb separately using some alternative (simpler) serialization format.  This could lag well behind the main chain (say 1000 blocks).

Alternatively, we could add a snapshot of the state into lokid releases (sort of like a hard-coded checkpoint) so that upgrades can start rescanning from a little while before the last release rather than all the way back to the SN launch height.

**Comment by Doy-lee** [comment]
Added in: https://github.com/loki-project/loki/pull/815
Merged to master in: #883
