### ISSUE TITLE
Decommission at point of stake 

### ISSUE THREAD

**Issue by Lucifer1903** [loki-project/loki#765]
**Describe the bug**
In the same block that the service node is staked it is decommissioned. 

**To Reproduce**
Unlock stake and wait 15 days until unlock. As soon as stake unlocks run prepare_registration on the service node deamon. Then run register_service_node in the wallet. If this is performed fast enough (before the next block) then the service nodes gets staked and is decommissioned at the same time. 

**Expected behaviour**
Service node is staked and given 2 hours of credit (without being decommissioned) 

**Current Behaviour**
Service node is staked but decommissioned 

**Screenshots or Logs**
![sketch-1564296583830](https://user-images.githubusercontent.com/29006257/62003286-d737e800-b10c-11e9-8058-07fd737c9747.png)
![sketch-1564296747091](https://user-images.githubusercontent.com/29006257/62003292-fe8eb500-b10c-11e9-82b3-b5a2356008a7.png)

**Additional Information (please complete the following information):**
 - Operating System: Ubuntu 18.0x
 - Version of Loki daemon 4.0.3

**Comment by darthInvad0r** [comment]
This also happened to me, [Here is the corresponding snode log file](https://files.catbox.moe/kf834e.gz). The registration takes place at 2019-07-25 23:17:40.757, 20 minutes after the node was de-registered. This was also on Ubuntu 18.04

**Comment by Doy-lee** [comment]
Fixed in #831 
Merged to master in #883
