### ISSUE TITLE
Wrong amount of blocks until unlock displayed

### ISSUE THREAD

**Issue by Lucifer1903** [loki-project/loki#766]
**Describe the bug**
print_sn_status shows wrong amount of blocks until unlock. 

**To Reproduce**
print_sn_status when 1 block until unlock 

**Expected behaviour**
Should show 1 block until unlock 

**Current Behaviour**
Shows a very large amount of blocks until unlock but still unlocks after 1 block 

**Screenshots or Logs**
![DSC_2568](https://user-images.githubusercontent.com/29006257/62003451-fafc2d80-b10e-11e9-82da-17290eb33b66.JPG)

**Additional Information (please complete the following information):**
 - Operating System: Ubuntu 18.0x
 - Version of Loki daemon 4.0.3

**Comment by Doy-lee** [comment]
Fixed in #894
