### ISSUE TITLE
Fee adjustment ideas (for v5)

### ISSUE THREAD

**Issue by jagerman** [loki-project/loki#787]
Our fee structure as of 4.x is a little bit wonky: we increased the fees 80x in #663 to prevent tx spam attacks, but this has had some unintended consequences:

1. tx fees for large transactions are unnecessarily high.
2. fees for higher priorities are insane

## TX fees are too high for large txes

On the first issue, a sweep of a bunch of small inputs (e.g. from SN rewards in a wallet that hasn't been swept in a while) results in a fairly substantial fee.  A 130-input sweep like this one, for example:

https://lokiblocks.com/tx/7b13172d9f4a085b26a78171d3d25cba762143fa8d2c16a2755ecf40b885ba6d

incurs a 1.64 LOKI fee.  (There are [two](https://lokiblocks.com/tx/a8a3f270532ada6811c72432d880d8b568076d9ba842a46a3ba18d0b9b5fa78d) [other](https://lokiblocks.com/tx/818158e18372cf3aa13e284264f73d56419f61690ebc5686c8bc03d8baf80f9a) large txes on the chain in the same or previous block, so it looks like this was a sweep of around 330 inputs that got split into three transactions with total incurred fees of 4.2 LOKI).

But this seems like a fee increase that isn't accomplishing anything because this is only three inputs: our goal with #663 was to make *inputs* expensive to discourage blockchain spamming; making blockchain data expensive was an unintended consequence of that adjustment.

## Insane high priority fees

https://github.com/loki-project/loki-electron-gui-wallet/issues/97 is worth a read: sending a moderate sized TX at the highest priority right now resulted in a 380 LOKI fee (it would have been 0.380 LOKI at minimum priority).  Even at "elevated" priority the fee would have been 9.5 LOKI, which still seems uselessly high.

So scaling up our fees as we did made the higher priority fees way too high.

# Proposed solution

So to summarize a few example transactions, in v5 we currently have:

0.04 LOKI for an "unimportant" (i.e. lowest) priority, minimum-size (~2.4kB) TX
4.20 LOKI for the 330-input sweep, "unimportant" priority sweep I referenced above
0.20 LOKI for a "normal" priority, minimum size TX
380 LOKI for the highest-priority, medium size (22kB) TX I referenced above

In #663 we basically just scaled up fees, but we did it with a focus only on the minimum, small tx fee.  So the above in v3 were more like:

0.0005 LOKI for an "unimportant" (i.e. lowest) priority, minimum-size (~2.4kB) TX
0.0525 LOKI for the 330-input sweep, "unimportant" priority sweep I referenced above
0.0025 LOKI for a "normal" priority, minimum size TX
23.75 LOKI for the highest-priority, medium size (22kB) TX I referenced above

I think we can do better that lets us keep TX fees reasonable for more transactions without being too cheap for small transactions by using a fixed + per-byte fee structure:

TXFEE = FIXED + PERBYTE × TXBYTES

where (I'm just throwing this out off the top of my head; we can have more discussion on the specific values we use):

FIXED = {0.04, 0.2, 1, 5} LOKI, based on the 1-4 priority level

PERBYTE meanwhile could go back to our v3 TX fees of about 1/80 of the current fee level.

So then the 4.6 LOKI sweep above would become (0.04 × 3) + (0.06) = 0.18 LOKI, and the 380 LOKI priority TX would become a more reasonable 5 + 4.75 LOKI fee (still high, but not stupidly high).  Meanwhile someone who wanted to flood the chain with as many TXes as possible to attempt a future de-anonymizing attack would still have to pay 0.0405 LOKI per transaction:

0.0405 LOKI for an "unimportant" (i.e. lowest) priority, minimum-size (~2.4kB) TX
0.1775 LOKI for the 330-input sweep, "unimportant" priority sweep I referenced above
0.2025 LOKI for a "normal" priority, minimum size TX
9.75 LOKI for the highest-priority, medium size (22kB) TX I referenced above

We could bring up the bottom fixed component a bit as well, to something like {0.1, 0.3, 1, 5} to bring that base fee floor up further without incurring a noticeably higher cost of sweeping—which from the point of view of a de-anonymizing attack are no more harmful than small transactions.  That would result in approximately:

0.1005 LOKI for a minimum-size, unimportant-priority transaction
0.3575 LOKI for the unimportant-priority 330-input sweep
0.3025 LOKI for a "normal" priority, small tx
9.75 LOKI (unchanged) for the highest-priority, medium size (22kB) TX I referenced above

Of course there are various other possibilities we can explore for the fee components here, but I think this sort of fee structure would be an improvement.

**Comment by jagerman** [comment]
Someone asked about this earlier today: note that the change I describe above requires a hard fork, so can come in with v5 at the earliest.

**Comment by KeeJef** [comment]
Yeah i don't mind this change, the 80x change was just based on rough calculations and merged fairly quickly to help mitigate a possible attack, i think this should also be combined with some work in the Loki GUI/Wallet to more clearly set out what different fee levels mean.

"Fast" and "Fastest" are confusing labels when you consider your TX wont really go any faster since most blocks are not full enough to leave transactions in the TX pool. Maybe we should only show different fee levels when the TX pool is sufficiently bloated.

**Comment by jagerman** [comment]
Thinking about this a little more, our concern here is actually the number of outputs created, *not* the number of transactions.  So a formula of:

TXFEE = PEROUTPUT × OUTPUTS + PERBYTE × TXBYTES

would be more appropriate than a single fixed per-TX fee.  So targeting the same 0.04 base for a simple tx, this would be something like:

PEROUTPUT = {0.02, 0.1, 0.5, 2.5}   (depending on priority)

Which would keep all the same values in my first fee suggestion above (that is, 0.0405, 0.1775, 0.2025, 9.75), assuming all are normal two output transactions.

What would get more expensive are multi-output transactions, such as a TX that sends to 15 people at once (16 outputs created in total, including the change).  But that's *good* from the point of view of keeping output creation from being too cheap.

**Comment by Doy-lee** [comment]
Merged to master: https://github.com/loki-project/loki/pull/883
