### ISSUE TITLE
Long sync times & peer connection wonkiness

### ISSUE THREAD

**Issue by jagerman** [loki-project/loki#789]
Several users have reported very long sync times with the v4.0.3 release (I've seen the same for current dev).  The connection counts are really wonky, and seem related:

> Height: 165554/334487 (49.5%) on mainnet, not mining, net hash 12.79 MH/s, v10, up to date, 35(out)+505(in) connections, uptime 0d 16h 50m 52s

It also chews memory like crazy -- it will sync hundreds of chunks of blocks in advance while going very, very slow at actually downloading and applying the first block in the chunk.  But it's more than just being slow, CPU use is also very high for the slowness of the sync.

Running with `--out-peers 8 --in-peers 8` seems to improve the situation considerably: sync time speeds up considerably and CPU usage goes down.  Running with just `--out-peers 8` doesn't appear to do anything (the reported out peers gets much higher than 8).

**Comment by Doy-lee** [comment]
Something real funky going on here. I don't get more than 8 reported peers when trying to sync using the release.

**Comment by jagerman** [comment]
Should be fixed by #794.
