### ISSUE TITLE
Mac issue

### ISSUE THREAD

**Issue by monamifoto** [loki-project/loki#79]
10.13.4

Couldnt get gui to work, kept crashing unexpected so telegram admin said to try CLI.

downloaded cli and as Chris McCabe suggested 'Try to run lokid - it should sync the blockchain for you'

Did not work, terminal just said:

Illegal instruction: 4
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

then nothing.

**Comment by Doy-lee** [comment]
Hi, could you try these binaries and also get some specs on the machine you're running?

https://loki.network/wp-content/uploads/2018/05/loki-mac64-v0.1.0-o2.zip
SHA: 5a611eba916f6038f9f78d717e5fdf43cf9690cfc7ed7cbbce3aed6490cfa2ea

**Comment by monamifoto** [comment]
Hi, when I try running lokid terminal opens up and says:
Illegal instruction: 4
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
Deleting expired sessions...none found.

[Process completed]


Spec is macbook 2013, 16gb ram, osx 10.13.4, 2.6 i7 - decent enough spec

trying loki-wallet-cli gives the same result

Illegal instruction: 4
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

**Comment by Doy-lee** [comment]
Seem to be getting this issue a couple of times from macbook users who have upgraded to latest OSX version. 

I've attached some new binaries worth testing.
https://loki.network/wp-content/uploads/2018/05/lokid-mac64-v0.1.0-osx-min-version1010.zip

Thanks in advance for testing.

**Comment by monamifoto** [comment]
hey, this seems to work.

Can you get this into a gui ?

**Comment by crtlib** [comment]
Have run into this issue as well. These binaries are working fine!

> I've attached some new binaries worth testing.
https://loki.network/wp-content/uploads/2018/05/lokid-mac64-v0.1.0-osx-min-version1010.zip

And yes, I'm on the latest OSX version.

**Comment by Doy-lee** [comment]
Great to hear that its working. I've replicated the build steps onto the gui which can be checked at https://github.com/loki-project/loki-gui/issues/20

These new binaries will be replacing the ones in the release page shortly. Closing issue and GUI issues to be redirected to the thread link above.
