### ISSUE TITLE
Stake through the RPC but the transaction has not been chained.

### ISSUE THREAD

**Issue by syyongx** [loki-project/loki#795]
Input:

curl -X POST http://127.0.0.1:61052/json_rpc \
-H 'Content-Type: application/json' \
-d @- << EOF
{
  "jsonrpc":"2.0",
  "id":"0",
  "method":"stake",
  "params": {
    "destination": "L6J2jXx5R23AAagWsSzUSU83cKRZ7cfK6Az2rZnSU2wYGAD6bSBcgAfR8zhX5RLC1ni1Sa4nPWSb7DVDH6rhDuDd8YM7qJp",
    "amount": 16606707468131,
    "subaddr_indices": [0],
    "service_node_key": "4882f5bf36a57cc54ddadb93eaee3ea1156b44dc490f69436b67eac61c9a5737",
    "priority": 0,
    "get_tx_key": true,
    "do_not_relay": true, 
    "get_tx_hex": false,
    "get_tx_metadata": false
  }
}
EOF

Output:
{
    "amount":16606707468131,
    "fee":44329020,
    "multisig_txset":"",
    "tx_hash":"1d6bd774a08b08a8fc46bd86c8654ae08aaa076788efa82a3ddbce2c58f6b4f6",
    "tx_key":"e0971e989757f338d11a34bd11cf5e089c4851d32fdea1fbb5e349eceb86e706",
    "unsigned_txset":""
}

But the tx_hash can't find it in explorer. I have checked my Block Height is the latest and the wallet version is 4.0.3

**Comment by jagerman** [comment]
The problem is almost certainly here:

> "do_not_relay": true,

The easiest would be to set it to false.

(It you want to do it in two steps it should be possible to submit the transaction this way, but you'll need to change `"get_tx_hex": false,` to `true`, to get the tx data, then submit the resulting transaction via the `relay_tx` RPC call.)

**Comment by syyongx** [comment]
@jagerman When i set "do_not_relay" to false, is successed, thank you very much.
