### ISSUE TITLE
How to create UI my daemon file is successfully installed 

### ISSUE THREAD

**Issue by Rockeronhunt** [loki-project/loki#83]
i installed my loki project in my server but it does not create any ui . but i want its UI(for reference find the screen shot also)
I dont understood how to do dis

for reference https://blockgen.net/setup-your-own-mining-pool/

![unompfront-1024x525](https://user-images.githubusercontent.com/32458821/40872068-5f2cf30c-6665-11e8-9227-d5a17e7e7cf1.png)

**Comment by Doy-lee** [comment]
The daemon by itself has no facilities to provide a front-end for such services. You will need to look for Cryptonight compatible software that connect to the daemon.
