### ISSUE TITLE
Don't send uptime proof until we've heard from the storage server

### ISSUE THREAD

**Issue by jagerman** [loki-project/loki#871]
We send an uptime proof initially (IIRC for the first hour) without having heard from the storage server, but this can mislead operators who think everything is working right because an uptime proof goes out.

Since the storage server pings quite frequently, I think we should require such a ping before sending any uptime proof.

**Comment by jagerman** [comment]
Also I think we can add to the new `lokid status` line for SNs a "NO STORAGE SERVER" status when we haven't heard from it.

**Comment by Doy-lee** [comment]
This sounds reasonable given there's evidence of this biting operators during the setup process. Initially the concern was that the 5 minutes in between checks or whatever the duration was too long to wait at startup, but this can be worked around by adding an uptime proof check after the first initial ping from storage server.

**Comment by jagerman** [comment]
There's already a 5 minute delay now (the uptime proof runs every 5 minutes and things are usually not ready when the first one fires), so I don't think we'd delay things.  But if the ping could trigger a proof going out that would actually improve things.

**Comment by jagerman** [comment]
Fixed in #874
