### ISSUE TITLE
MSYS2 on Windows 10x64 with a fresh build will not compile CLI tools. Halts on db_lmdb.cpp compile error 2.

### ISSUE THREAD

**Issue by mechanator** [loki-project/loki#904]
**Describe the bug**
MSYS2 on Windows 10x64 with a fresh build will not compile the Loki CLI tools. Halts on lmdb.cpp compile error 2. 
Msys2 fails to start also due to missing dependency "git" not included on readme.md instructions.
MSYS2 will also fail building the linux static build binaries using Windows MSYS2 to build the linux binaries in the same exact spot.
See attached screenshot of the compilation error:
![failed-lmdb_cpp_h_comile_endian_boost_call](https://user-images.githubusercontent.com/40085316/67062384-01031880-f118-11e9-85c9-4d8daccefed4.png)

**To Reproduce**
Install Windows 10, no third party applications or compilers/dev tools to eliminate confusion.
Launch the MS Edge browser
go to https://github.com/loki-project/loki with the edge browser.
Follow steps exactly for installation of MSYS2 and compiling for Windows MSYS2 compilation.

"Update packages using pacman:

pacman -Syu
Exit the MSYS shell using Alt+F4 when you get a warning stating: "terminate MSYS2 without returning to shell and check for updates again/for example close your terminal window instead of calling exit"

pacman -Syu
Update packages again using pacman:

(added) pacman -S git

  pacman -Syu  
Install dependencies:

To build for 64-bit Windows:

pacman -S mingw-w64-x86_64-toolchain make mingw-w64-x86_64-cmake mingw-w64-x86_64-boost mingw-w64-x86_64-openssl mingw-w64-x86_64-zeromq mingw-w64-x86_64-libsodium mingw-w64-x86_64-hidapi

Execute code pull for Windows 10 X 64 from git within the MSYS2 terminal MingW64.

"git clone --recursive https://github.com/loki-project/loki.git"

Then execute compilation.
"cd loki"
"make release-static-win64"
(compiler executes and stops prematurely).

**Expected behavior**
What is the expected behavior if the steps above are followed:

Compilation of the binaries with non modified source code, static linked, running on Windows 10x64

**Current Behaviour**
What is the current behaviour if the steps to reproduce are followed:

The compiler sequence fails to completely compile and no binaries are produced in the /build/MINGW64_NT10.0-18362\master\release\bin directory.

makefile reports error 2 and halts.  Something to do with db_lmdb.cpp and db_lmdb.h calling BOOST STATIC ASSERT library within MINGW64 /include/boost/conversion.hpp instantiating void boost::endian::native_to_little_inplace(EndianReversibleInplace&) with [ EndianReverseibleInplace = cryptonote::blob_type] . 

**Screenshots or Logs**
If applicable, add screenshots or logs to help explain your problem.

See problem definition screen output.

Consistently fails even if optional dependencies are installed, whether a call to  
" cd loki && git submodule init && git submodule update"  is executed.

Also fails on execution of "make release-static-linux-x86_64" at the same location in the source code. 

**Additional Information (please complete the following information):**
 - Operating System: [e.g. Ubuntu 16.04, Windows 10]

Windows 10 x64 built 10/17/2019 Version 1903 OS build 183262.418.
Previous builds before last batch of windows updates also failed from two weeks ago. Those attempts were on a dirty OS build with other compilers and cmake 3.45 installed for Visual Studio 2019
-  Local or Remote node
Locally built as Administrator.

 - Version of Loki daemon, or most recent commit hash.
master branch as of 10/17/2019 
Latest commit 973f9de 2 days ago ? 

Well, it's time to  circle the wagons, looks there is like trouble in Endian country.  :}
At the very least update the readme.md since you need "git" as a Msys2 package to even get the source code pulled into the computer with the exception of a downloaded zip file.

@jagerman

**Comment by Doy-lee** [comment]
Looks like they added to Boost 1.7.1 (assuming Msys2 is packaging the latest boost)
```
template<class T> struct is_endian_reversible: boost::integral_constant<bool,
    boost::is_class<T>::value || ( boost::is_integral<T>::value && !boost::is_same<T, bool>::value )>
{
};
```

And blob_type is uint8_t, which doesn't need to be endian swapped.

**Comment by Doy-lee** [comment]
Fix is PRed into master and dev. Should be able to build now

**Comment by mechanator** [comment]
Nope. fails at 86% in linking phase at wallet-rpc-server. Error 2,

**Comment by mechanator** [comment]
Word salad from the linker at wallet_rpc_server.cpp , something related to boost again .
"undefined referene to __memcpy_chk'

[output.txt](https://github.com/loki-project/loki/files/3744196/output.txt)

**Comment by mechanator** [comment]
Commented out line 666 from Cmakelists.txt. The code now compiles and links, but loki-wallet-cli.exe stops running saying libprotobuf.dll is missing. Added that .dll and then loki-wallet-cli.exe stops abruptly.
![image](https://user-images.githubusercontent.com/40085316/67129328-3872d300-f1b3-11e9-8075-093a719256db.png)

**Comment by Doy-lee** [comment]
Try cherry-picking #907 to fix the `__memcpy_chk` failure. I'm curious what other DLL loki-wallet-cli is requesting. You can use `ldd loki-wallet-cli` in the msys terminal.

You should expect to see something like this, note that this build, following the readme doesn't have any dependencies on `protobuf` DLLs.
```
$ ldd loki-wallet-cli
        ntdll.dll => /c/Windows/SYSTEM32/ntdll.dll (0x7ffc184c0000)
        KERNEL32.DLL => /c/Windows/System32/KERNEL32.DLL (0x7ffc18170000)
        KERNELBASE.dll => /c/Windows/System32/KERNELBASE.dll (0x7ffc14b00000)
        ADVAPI32.dll => /c/Windows/System32/ADVAPI32.dll (0x7ffc183e0000)
        msvcrt.dll => /c/Windows/System32/msvcrt.dll (0x7ffc182f0000)
        sechost.dll => /c/Windows/System32/sechost.dll (0x7ffc17aa0000)
        RPCRT4.dll => /c/Windows/System32/RPCRT4.dll (0x7ffc173c0000)
        CRYPT32.dll => /c/Windows/System32/CRYPT32.dll (0x7ffc14920000)
        ucrtbase.dll => /c/Windows/System32/ucrtbase.dll (0x7ffc14da0000)
        MSASN1.dll => /c/Windows/System32/MSASN1.dll (0x7ffc14510000)
        SETUPAPI.dll => /c/Windows/System32/SETUPAPI.dll (0x7ffc17b40000)
        cfgmgr32.dll => /c/Windows/System32/cfgmgr32.dll (0x7ffc14790000)
        IPHLPAPI.DLL => /c/Windows/SYSTEM32/IPHLPAPI.DLL (0x7ffc13aa0000)
        bcrypt.dll => /c/Windows/System32/bcrypt.dll (0x7ffc156c0000)
        SHELL32.dll => /c/Windows/System32/SHELL32.dll (0x7ffc15bb0000)
        shcore.dll => /c/Windows/System32/shcore.dll (0x7ffc18230000)
        combase.dll => /c/Windows/System32/combase.dll (0x7ffc156f0000)
        bcryptPrimitives.dll => /c/Windows/System32/bcryptPrimitives.dll (0x7ffc147e0000)
        windows.storage.dll => /c/Windows/System32/windows.storage.dll (0x7ffc14f70000)
        msvcp_win.dll => /c/Windows/System32/msvcp_win.dll (0x7ffc14880000)
        profapi.dll => /c/Windows/System32/profapi.dll (0x7ffc144c0000)
        powrprof.dll => /c/Windows/System32/powrprof.dll (0x7ffc14530000)
        shlwapi.dll => /c/Windows/System32/shlwapi.dll (0x7ffc17150000)
        GDI32.dll => /c/Windows/System32/GDI32.dll (0x7ffc18390000)
        gdi32full.dll => /c/Windows/System32/gdi32full.dll (0x7ffc14590000)
        USER32.dll => /c/Windows/System32/USER32.dll (0x7ffc17210000)
        win32u.dll => /c/Windows/System32/win32u.dll (0x7ffc14ea0000)
        kernel.appcore.dll => /c/Windows/System32/kernel.appcore.dll (0x7ffc144f0000)
        cryptsp.dll => /c/Windows/System32/cryptsp.dll (0x7ffc14860000)
        WS2_32.dll => /c/Windows/System32/WS2_32.dll (0x7ffc170a0000)
        CRYPTBASE.DLL => /c/Windows/SYSTEM32/CRYPTBASE.DLL (0x7ffc13f10000)
```

**Comment by mechanator** [comment]
I ran  ``ldd loki-wallet-cli  : 
	ntdll.dll => /c/WINDOWS/SYSTEM32/ntdll.dll (0x7fff210e0000)
	KERNEL32.DLL => /c/WINDOWS/System32/KERNEL32.DLL (0x7fff20780000)
	KERNELBASE.dll => /c/WINDOWS/System32/KERNELBASE.dll (0x7fff1e920000)
	ADVAPI32.dll => /c/WINDOWS/System32/ADVAPI32.dll (0x7fff1f210000)
	msvcrt.dll => /c/WINDOWS/System32/msvcrt.dll (0x7fff20e50000)
	sechost.dll => /c/WINDOWS/System32/sechost.dll (0x7fff1fe30000)
	RPCRT4.dll => /c/WINDOWS/System32/RPCRT4.dll (0x7fff20490000)
	CRYPT32.dll => /c/WINDOWS/System32/CRYPT32.dll (0x7fff1ebd0000)
	ucrtbase.dll => /c/WINDOWS/System32/ucrtbase.dll (0x7fff1f090000)
	MSASN1.dll => /c/WINDOWS/System32/MSASN1.dll (0x7fff1e050000)
	SETUPAPI.dll => /c/WINDOWS/System32/SETUPAPI.dll (0x7fff1ffb0000)
	cfgmgr32.dll => /c/WINDOWS/System32/cfgmgr32.dll (0x7fff1eea0000)
	bcrypt.dll => /c/WINDOWS/System32/bcrypt.dll (0x7fff1e7f0000)
	SHELL32.dll => /c/WINDOWS/System32/SHELL32.dll (0x7fff1f710000)
	shcore.dll => /c/WINDOWS/System32/shcore.dll (0x7fff20860000)
	combase.dll => /c/WINDOWS/System32/combase.dll (0x7fff20970000)
	bcryptPrimitives.dll => /c/WINDOWS/System32/bcryptPrimitives.dll (0x7fff1ed20000)
	windows.storage.dll => /c/WINDOWS/System32/windows.storage.dll (0x7fff1e070000)
	msvcp_win.dll => /c/WINDOWS/System32/msvcp_win.dll (0x7fff1eda0000)
	profapi.dll => /c/WINDOWS/System32/profapi.dll (0x7fff1e010000)
	powrprof.dll => /c/WINDOWS/System32/powrprof.dll (0x7fff1dfc0000)
	UMPDC.dll => /c/WINDOWS/System32/UMPDC.dll (0x7fff1dfb0000)
	shlwapi.dll => /c/WINDOWS/System32/shlwapi.dll (0x7fff20720000)
	GDI32.dll => /c/WINDOWS/System32/GDI32.dll (0x7fff205b0000)
	win32u.dll => /c/WINDOWS/System32/win32u.dll (0x7fff1e840000)
	gdi32full.dll => /c/WINDOWS/System32/gdi32full.dll (0x7fff1eef0000)
	USER32.dll => /c/WINDOWS/System32/USER32.dll (0x7fff1f3a0000)
	kernel.appcore.dll => /c/WINDOWS/System32/kernel.appcore.dll (0x7fff1e030000)
	cryptsp.dll => /c/WINDOWS/System32/cryptsp.dll (0x7fff1e820000)
	WS2_32.dll => /c/WINDOWS/System32/WS2_32.dll (0x7fff1f6a0000)
	IPHLPAPI.DLL => /c/WINDOWS/SYSTEM32/IPHLPAPI.DLL (0x7fff1d530000)
	libprotobuf.dll => /mingw64/bin/libprotobuf.dll (0x70040000)
	libwinpthread-1.dll => /mingw64/bin/libwinpthread-1.dll (0x64940000)
	libgcc_s_seh-1.dll => /mingw64/bin/libgcc_s_seh-1.dll (0x61440000)
	libstdc++-6.dll => /mingw64/bin/libstdc++-6.dll (0x6fc40000)
	zlib1.dll => /mingw64/bin/zlib1.dll (0x62e80000)
	CRYPTBASE.DLL => /c/WINDOWS/SYSTEM32/CRYPTBASE.DLL (0x7fff1d9f0000)

Here is an attached copy for reference.
[ldd_loki_wallet-cli.txt](https://github.com/loki-project/loki/files/3753196/ldd_loki_wallet-cli.txt)

**Comment by mechanator** [comment]
The difference looks like these are reference in the executable that is different from yours:
UMPDC.dll => /c/WINDOWS/System32/UMPDC.dll (0x7fff1dfb0000)
IPHLPAPI.DLL => /c/WINDOWS/SYSTEM32/IPHLPAPI.DLL (0x7fff1d530000)
libprotobuf.dll => /mingw64/bin/libprotobuf.dll (0x70040000)
libwinpthread-1.dll => /mingw64/bin/libwinpthread-1.dll (0x64940000)
libgcc_s_seh-1.dll => /mingw64/bin/libgcc_s_seh-1.dll (0x61440000)
libstdc++-6.dll => /mingw64/bin/libstdc++-6.dll (0x6fc40000)
zlib1.dll => /mingw64/bin/zlib1.dll (0x62e80000)

**Comment by Doy-lee** [comment]
Can I get a copy of your build log? 

Protobuf depends on zlib and gcc_s_seh-1. But even if I add those packages to mingw, they still link against the static variants.

**Comment by mechanator** [comment]
ok, I discovered why protobuf and libprotobuff.dll was being included. I was working on another project, and it required the following dependencies. Even though they were not included with loki, for some reason the linker is attempting to included them.
Removed dependencies installed and attempting to recompile/link. 
With and without the lines:
663  if(CMAKE_BUILD_TYPE STREQUAL "Release" AND NOT MINGW)
and
666  set(CXX_SECURITY_FLAGS "${CXX_SECURITY_FLAGS} -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1")

666 was also attempted with it commented out.
----Last output from Msys2:
[ 75%] Building CXX object src/blockchain_db/CMakeFiles/obj_blockchain_db.dir/lmdb/db_lmdb.cpp.obj
In file included from C:/msys64/mingw64/include/boost/type_index/stl_type_index.hpp:32,
                 from C:/msys64/mingw64/include/boost/type_index.hpp:29,
                 from C:/msys64/mingw64/include/boost/any.hpp:20,
                 from C:/msys64/mingw64/include/boost/program_options/value_semantic.hpp:12,
                 from C:/msys64/mingw64/include/boost/program_options/options_description.hpp:13,
                 from C:/msys64/mingw64/include/boost/program_options.hpp:15,
                 from C:/msys64/home/mecha/loki/src/blockchain_db/blockchain_db.h:35,
                 from C:/msys64/home/mecha/loki/src/blockchain_db/lmdb/db_lmdb.h:31,
                 from C:/msys64/home/mecha/loki/src/blockchain_db/lmdb/db_lmdb.cpp:29:
C:/msys64/mingw64/include/boost/endian/conversion.hpp: In instantiation of 'void boost::endian::native_to_little_inplace(EndianReversibleInplace&) [with EndianReversibleInplace = cryptonote::blob_type]':
C:/msys64/home/mecha/loki/src/blockchain_db/lmdb/db_lmdb.cpp:2278:54:   required from here
C:/msys64/mingw64/include/boost/endian/conversion.hpp:330:5: error: static assertion failed: detail::is_endian_reversible_inplace<EndianReversibleInplace>::value
  330 |     BOOST_STATIC_ASSERT( detail::is_endian_reversible_inplace<EndianReversibleInplace>::value );
      |     ^~~~~~~~~~~~~~~~~~~
C:/msys64/mingw64/include/boost/endian/conversion.hpp: In instantiation of 'void boost::endian::little_to_native_inplace(EndianReversibleInplace&) [with EndianReversibleInplace = cryptonote::blob_type]':
C:/msys64/home/mecha/loki/src/blockchain_db/lmdb/db_lmdb.cpp:2286:54:   required from here
C:/msys64/mingw64/include/boost/endian/conversion.hpp:311:5: error: static assertion failed: detail::is_endian_reversible_inplace<EndianReversibleInplace>::value
  311 |     BOOST_STATIC_ASSERT( detail::is_endian_reversible_inplace<EndianReversibleInplace>::value );
      |     ^~~~~~~~~~~~~~~~~~~
make[3]: *** [src/blockchain_db/CMakeFiles/obj_blockchain_db.dir/build.make:76: src/blockchain_db/CMakeFiles/obj_blockchain_db.dir/lmdb/db_lmdb.cpp.obj] Error 1
make[3]: Leaving directory '/home/mecha/loki/build/MINGW64_NT-10.0-18362/_HEAD_detached_at_v5.1.2_/release'
make[2]: *** [CMakeFiles/Makefile2:2795: src/blockchain_db/CMakeFiles/obj_blockchain_db.dir/all] Error 2
make[2]: Leaving directory '/home/mecha/loki/build/MINGW64_NT-10.0-18362/_HEAD_detached_at_v5.1.2_/release'
make[1]: *** [Makefile:141: all] Error 2
make[1]: Leaving directory '/home/mecha/loki/build/MINGW64_NT-10.0-18362/_HEAD_detached_at_v5.1.2_/release'
make: *** [Makefile:156: release-static-win64] Error 2

**Comment by mechanator** [comment]
Attempting another build with fresh install of Msys2 to be sure.

**Comment by Doy-lee** [comment]
You should be able to build with and without libprotobuf. It's required for Trezor. But building with protobuf should pull in the static variants. The full build log might reveal why it's pulling in the dynamic library variant of protobuf rather than the static version.

You can't build v5.1.2 as that tags a commit that doesn't build on a fresh msys with the latest packages. Build master with #907 cherry-picked to fix the FORTIFY_SOURCE issue and the static assert on endian conversion is fixed in master.

**Comment by mechanator** [comment]
Commented out lines 662-667 to remove the requirement for fortified source. It compiles to complete linking and daemon and wallet apps runs.
 # if those don't work for your compiler, single it out where appropriate
  #if(CMAKE_BUILD_TYPE STREQUAL "Release")
  #  set(C_SECURITY_FLAGS "${C_SECURITY_FLAGS} -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1")
  #  set(C_SECURITY_FLAGS "${C_SECURITY_FLAGS} -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1")
  #  set(CXX_SECURITY_FLAGS "${CXX_SECURITY_FLAGS} -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1")
  #endif()
