### ISSUE TITLE
Help with some doubts

### ISSUE THREAD

**Issue by jonatanrinckus** [loki-project/loki#94]
Hi guys

We are doing a fork of your code, the code is almost all configured, but we have some doubts, could you help us?

These are our doubts:

1) How to change the max supply in your code? We would like to set it to a maximum allowance of 8 million with the emission factor at 22, which in the default setting of cryptonote would generate 1.9 reward per block initially.

2) The governance wallet, it should receive 5% of the blocks, right? Our governance wallet is not receiving any rewards.

Thank you in advance.

**Comment by jcktm** [comment]
1. Look at `get_block_reward` and tweak the constants in cryptonote_config.h
2. How did you put your governance key in the genisis block?

**Comment by jonatanrinckus** [comment]
Hello, thanks.

I understand the changes in the constants to change the reward, what I need to understand is how you get the max supply of 150 millions? Is it because the base_reward is near to 0? I made some calculations and get it, I'm right?

The EMISSION_LINEAR_BASE(=288230376151711000), what is the purpose and effects?

About the governance, you say to uncomment this line?

https://github.com/loki-project/loki/blob/master/src/cryptonote_core/cryptonote_tx_utils.cpp#L297

**Comment by jonatanrinckus** [comment]
It has the information about the governance fee in the block, but, nothing received in the governance  wallet

![photo5023976804553172946](https://user-images.githubusercontent.com/19454127/42101528-b4e78bf6-7b99-11e8-8281-1e6a2de16740.jpg)
![photo5023976804553172947](https://user-images.githubusercontent.com/19454127/42101531-b67d555e-7b99-11e8-86df-758d7a6a839d.jpg)
![image](https://user-images.githubusercontent.com/19454127/42101554-c5404628-7b99-11e8-8a2a-f920d8ad4014.png)

**Comment by LordMajestros** [comment]
> Hello, thanks.
> 
> I understand the changes in the constants to change the reward, what I need to understand is how you get the max supply of 150 millions? Is it because the base_reward is near to 0 when 150 million coin are mined? I made some calculations and get it, I'm right?
> 
> The EMISSION_LINEAR_BASE(=288230376151711000), what is the purpose and effects?
> 
@jrrcdev I don't know if you've figured this out yet but you can take a look at other cryptonote coins for notes on how to change the emission. You could also use http://forknote.net/ to customize your emission.

> About the governance, you say to uncomment this line?
> 
> https://github.com/loki-project/loki/blob/master/src/cryptonote_core/cryptonote_tx_utils.cpp#L297

The line numbers have changed since then. If you want to receive governance rewards and you are not currently, check that the governance wallet address in cryptonoteconfig.h is your chain's governance reward (this line https://github.com/loki-project/loki/blob/master/src/cryptonote_config.h#L186).
